from matching_engine.user_model import User

female_English = [

    User(
        name='Leo',
        age=24,
        gender='female',
        height=165,
        location='Johor',
        salary=3610,
        language='English',
        interests=['fitness', 'anime', 'cooking'],
        personality=[3, 2, 1, 3, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 31],
        preferred_salary_range=[3574, 6642],
        preferred_language='English',
        preferred_interests=['music', 'anime'],
        preferred_personality=[4, 5, 2, 2, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Wu Ao Jin',
        age=24,
        gender='female',
        height=158,
        location='KL',
        salary=8678,
        language='English',
        interests=['food', 'yoga','cooking'],
        personality=[5, 3, 2, 4, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[27, 35],
        preferred_salary_range=[6500, 11234],
        preferred_language='Malay',
        preferred_interests=['reading','gaming'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Tom',
        age=26,
        gender='female',
        height=166,
        location='Penang',
        salary=6091,
        language='English',
        interests=['travel', 'reading', 'music'],
        personality=[5, 3, 5, 4, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3440, 6194],
        preferred_language='English',
        preferred_interests=['tech', 'fitness'],
        preferred_personality=[1, 4, 5, 2, 3],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Gavin',
        age=23,
        gender='female',
        height=155,
        location='Selangor',
        salary=6753,
        language='English',
        interests=['travel', 'tech', 'anime'],
        personality=[3, 2, 4, 3, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[24, 27],
        preferred_salary_range=[3811, 6060],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 5, 5, 3, 2],
        preferred_height_range=[160, 174],
    ),
    User(
        name='Tan Ren',
        age=22,
        gender='female',
        height=170,
        location='Johor',
        salary=6123,
        language='English',
        interests=['movies', 'music','sports'],
        personality=[2, 1, 4, 2, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 26],
        preferred_salary_range=[6123, 7534],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[169, 181],
    ),
    User(
        name='Kylie',
        age=26,
        gender='female',
        height=165,
        location='Ipoh',
        salary=4130,
        language='English',
        interests=['gaming', 'travel', 'anime'],
        personality=[3, 5, 2, 3, 5],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3655, 5651],
        preferred_language='English',
        preferred_interests=['gaming', 'anime'],
        preferred_personality=[4, 4, 2, 4, 2],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Huang Yi Yang',
        age=24,
        gender='female',
        height=170,
        location='Selangor',
        salary=8845,
        language='English',
        interests=['fitness', 'gaming','reading'],
        personality=[5, 1, 5, 3, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[8745, 12735],
        preferred_language='English',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Chong Zi Han',
        age=28,
        gender='female',
        height=160,
        location='Penang',
        salary=7567,
        language='English',
        interests=['travel', 'reading','gaming'],
        personality=[4, 4, 2, 3, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[25, 32],
        preferred_salary_range=[7000, 9000],
        preferred_language='Malay',
        preferred_interests=['gaming','sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[160, 180],
    ),
   User(
        name='Yuri',
        age=24,
        gender='female',
        height=174,
        location='Selangor',
        salary=9778,
        language='English',
        interests=['music', 'cooking', 'fitness'],
        personality=[1, 4, 3, 2, 4],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[5762, 9724],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[4, 1, 4, 4, 2],
        preferred_height_range=[175, 184],
    ),
    User(
        name='Carl',
        age=23,
        gender='female',
        height=172,
        location='Selangor',
        salary=5761,
        language='English',
        interests=['reading', 'tech', 'cooking'],
        personality=[3, 5, 5, 1, 5],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[20, 34],
        preferred_salary_range=[5242, 11547],
        preferred_language='English',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 5, 3, 2, 4],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Oscar',
        age=29,
        gender='female',
        height=156,
        location='Selangor',
        salary=5843,
        language='English',
        interests=['sports', 'music', 'cooking'],
        personality=[4, 2, 2, 1, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[23, 29],
        preferred_salary_range=[5607, 9785],
        preferred_language='any',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 5, 3, 2, 4],
        preferred_height_range=[161, 175],
    ),
    User(
        name='Una',
        age=28,
        gender='female',
        height=175,
        location='Penang',
        salary=5526,
        language='English',
        interests=['tech', 'sports', 'travel'],
        personality=[2, 2, 2, 4, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5878, 10866],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[4, 4, 1, 2, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Samantha Lim',
        age=24,
        gender='female',
        height=168,
        location='Johor',
        salary=6245,
        language='English',
        interests=['music', 'reading', 'movies'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 28],
        preferred_salary_range=[6000, 8000],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 179],
    ),
    User(
        name='Wesley',
        age=22,
        gender='female',
        height=159,
        location='Penang',
        salary=6399,
        language='English',
        interests=['music', 'sports', 'gaming'],
        personality=[1, 4, 4, 4, 5],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[25, 29],
        preferred_salary_range=[3742, 6423],
        preferred_language='English',
        preferred_interests=['movies', 'fitness'],
        preferred_personality=[4, 2, 3, 1, 1],
        preferred_height_range=[163, 180],
    ),
    User(
        name='Wang Wen Hua',
        age=24,
        gender='female',
        height=170,
        location='Johor',
        salary=7454,
        language='English',
        interests=['music', 'cooking','reading'],
        personality=[3, 2, 1, 4, 4],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[23, 28],
        preferred_salary_range=[6321, 7767],
        preferred_language='any',
        preferred_interests=['sports', 'gaming'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[165, 181],
    ),
    User(
        name='Li Wei',
        age=25,
        gender='female',
        height=172,
        location='Selangor',
        salary=9134,
        language='English',
        interests=['fitness', 'music', 'gaming'],
        personality=[5, 1, 4, 3, 2],
        preferred_gender='male',
       preferred_location='Ipoh',
       preferred_age_range=[23, 30],
       preferred_salary_range=[8500, 10500],
       preferred_language='English',
       preferred_interests=['cooking'],
       preferred_personality=[3, 3, 2, 5, 3],
       preferred_height_range=[165, 180],
   ),
    User(
        name='Yvonne',
        age=33,
        gender='female',
        height=173,
        location='Johor',
        salary=4833,
        language='English',
        interests=['cooking', 'travel', 'reading'],
        personality=[4, 5, 1, 4, 1],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[24, 39],
        preferred_salary_range=[3284, 9552],
        preferred_language='any',
        preferred_interests=['fitness', 'music'],
        preferred_personality=[1, 2, 1, 3, 2],
        preferred_height_range=[170, 185],
    ),
     User(
        name='Mio',
        age=25,
        gender='female',
        height=160,
        location='Johor',
        salary=6894,
        language='English',
        interests=['streaming', 'cooking', 'gaming'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5525, 10829],
        preferred_language='English',
        preferred_interests=['anime', 'cleaning'],
        preferred_personality=[1, 1, 4, 5, 2],
        preferred_height_range=[170, 184],
    ),
   User(
        name='Melody',
        age=26,
        gender='female',
        height=159,
        location='Ipoh',
        salary=4919,
        language='English',
        interests=['gaming', 'movies', 'music'],
        personality=[5, 3, 2, 5, 2],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[25, 29],
        preferred_salary_range=[4633, 9445],
        preferred_language='English',
        preferred_interests=['travel', 'tech'],
        preferred_personality=[1, 1, 1, 5, 1],
        preferred_height_range=[162, 177],
    ),
    User(
        name='Queena',
        age=23,
        gender='female',
        height=175,
        location='Selangor',
        salary=10786,
        language='English',
        interests=['tech', 'travel', 'anime'],
        personality=[4, 1, 1, 1, 5],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[23, 31],
        preferred_salary_range=[9091, 12785],
        preferred_language='English',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[2, 4, 5, 3, 2],
        preferred_height_range=[155, 171],
    ),
    User(
        name='Freya',
        age=21,
        gender='female',
        height=158,
        location='KL',
        salary=7990,
        language='English',
        interests=['movies', 'travel', 'sports'],
        personality=[5, 2, 5, 1, 1],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 32],
        preferred_salary_range=[8779, 10865],
        preferred_language='English',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[1, 1, 2, 5, 2],
        preferred_height_range=[165, 183],
    ),
    User(
        name='Zhang Xiao Hua',
        age=26,
        gender='female',
        height=167,
        location='Ipoh',
        salary=7143,
        language='English',
        interests=['cooking', 'music', 'reading'],
        personality=[4, 3, 1, 3, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[24, 29],
        preferred_salary_range=[5867, 8945],
        preferred_language='any',
        preferred_interests=['sports', 'gaming'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Nate',
        age=25,
        gender='female',
        height=168,
        location='KL',
        salary=4013,
        language='English',
        interests=['cooking', 'sports', 'anime'],
        personality=[5, 5, 3, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3927, 6926],
        preferred_language='any',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[2, 1, 5, 3, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Grace Wong',
        age=25,
        gender='female',
        height=162,
        location='Melaka',
        salary=6456,
        language='English',
        interests=['travel', 'music','gaming'],
        personality=[3, 2, 3, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 30],
        preferred_salary_range=[5574, 8845],
        preferred_language='any',
        preferred_interests=['movies', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[159, 179],
    ),
    User(
        name='Uma',
        age=23,
        gender='female',
        height=164,
        location='Ipoh',
        salary=6652,
        language='English',
        interests=['anime', 'tech', 'gaming'],
        personality=[2, 2, 5, 3, 5],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[20, 29],
        preferred_salary_range=[3100, 5584],
        preferred_language='any',
        preferred_interests=['gaming', 'tech'],
        preferred_personality=[3, 5, 4, 1, 2],
        preferred_height_range=[171, 185],
    ),
    User(
        name='Li Zi Qi',
        age=27,
        gender='female',
        height=168,
        location='KL',
        salary=9556,
        language='English',
        interests=['gaming', 'travel','anime'],
        personality=[4, 2, 3, 4, 2],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[24, 31],
        preferred_salary_range=[7534, 13175],
        preferred_language='English',
        preferred_interests=['fitness','movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 181],
    ),
    User(
        name='Sunshine',
        age=23,
        gender='female',
        height=157,
        location='Selangor',
        salary=6753,
        language='English',
        interests=['travel', 'tech', 'anime'],
        personality=[3, 2, 4, 3, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[24, 27],
        preferred_salary_range=[4578, 6060],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 5, 5, 3, 2],
        preferred_height_range=[160, 176],
    ),
    User(
        name='Rose',
        age=20,
        gender='female',
        height=174,
        location='Selangor',
        salary=5225,
        language='English',
        interests=['movies', 'fitness', 'travel'],
        personality=[4, 4, 3, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4643, 9827],
        preferred_language='English',
        preferred_interests=['anime', 'fitness'],
        preferred_personality=[4, 2, 4, 3, 1],
        preferred_height_range=[175, 185],
    ),
    User(
        name='Sean',
        age=21,
        gender='female',
        height=167,
        location='KL',
        salary=7583,
        language='English',
        interests=['travel', 'music', 'anime'],
        personality=[5, 5, 1, 5, 5],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 28],
        preferred_salary_range=[6754, 12203],
        preferred_language='any',
        preferred_interests=['travel', 'reading'],
        preferred_personality=[3, 3, 5, 5, 4],
        preferred_height_range=[170, 180],
    ),
    User(
        name='Ma Bin',
        age=24,
        gender='female',
        height=174,
        location='Selangor',
        salary=10778,
        language='English',
        interests=['music', 'cooking', 'fitness'],
        personality=[1, 4, 3, 2, 4],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[5762, 11724],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[4, 1, 4, 4, 2],
        preferred_height_range=[173, 184],
    ),
    User(
        name='Liu Xiao',
        age=25,
        gender='female',
        height=165,
        location='Ipoh',
        salary=6756,
        language='English',
        interests=['reading', 'cooking', 'travel'],
        personality=[4, 2, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6123, 9567],
        preferred_language='English',
        preferred_interests=['gaming', 'sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[161, 180],
    ),
    User(
        name='Uno',
        age=28,
        gender='female',
        height=174,
        location='Penang',
        salary=5526,
        language='English',
        interests=['tech', 'sports', 'travel'],
        personality=[2, 2, 2, 4, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5878, 10866],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[5, 4, 1, 2, 2],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Olivia Cheng',
        age=27,
        gender='female',
        height=174, 
        location='Selangor',
        salary=6778, 
        language='English',
        interests=['sports', 'food','anime'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6123, 7567],
        preferred_language='English',
        preferred_interests=['reading', 'anime'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 181],
    ),


    User(
        name='Carmen',
        age=22,
        gender='female',
        height=161,
        location='KL',
        salary=6848,
        language='English',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 32],
        preferred_salary_range=[4894, 8810],
        preferred_language='English',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 2, 1, 4, 4],
        preferred_height_range=[161, 179],
    ),
    User(
        name='Cherry',
        age=25,
        gender='female',
        height=159,
        location='Penang',
        salary=3685,
        language='English',
        interests=['sports', 'tech', 'anime'],
        personality=[3, 4, 5, 5, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 29],
        preferred_salary_range=[3250, 7721],
        preferred_language='English',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[2, 4, 1, 4, 5],
        preferred_height_range=[162, 178],
    ),
     User(
        name='Zhen',
        age=25,
        gender='female',
        height=167,
        location='KL',
        salary=4013,
        language='English',
        interests=['cooking', 'sports', 'anime'],
        personality=[5, 4, 3, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3927, 6926],
        preferred_language='English',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[2, 1, 5, 3, 2],
        preferred_height_range=[169, 185],
    ),
     User(
        name='Bella',
        age=30,
        gender='female',
        height=163,
        location='KL',
        salary=3270,
        language='English',
        interests=['music', 'travel', 'cooking'],
        personality=[4, 2, 1, 2, 3],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3014, 7617],
        preferred_language='English',
        preferred_interests=['travel', 'cooking'],
        preferred_personality=[5, 1, 5, 4, 3],
        preferred_height_range=[168, 177],
    ),
    User(
        name='Zhao Lei',
        age=29,
        gender='female',
        height=163,
        location='Penang',
        salary=8856,
        language='English',
        interests=['reading', 'yoga','gaming'],
        personality=[4, 3, 3, 3, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[25, 31],
        preferred_salary_range=[7356, 9976],
        preferred_language='English',
        preferred_interests=['fitness','yoga'],
        preferred_personality=[4, 3, 2, 5, 3],
        preferred_height_range=[165, 182],
    ),
   User(
        name='Hai Nu',
        age=23,
        gender='female',
        height=154,
        location='Selangor',
        salary=6753,
        language='English',
        interests=['travel', 'tech', 'anime'],
        personality=[3, 2, 4, 3, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[24, 27],
        preferred_salary_range=[3675, 6060],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 5, 5, 3, 2],
        preferred_height_range=[160, 172],
    ),
    User(
        name='Shang',
        age=20,
        gender='female',
        height=166,
        location='KL',
        salary=7563,
        language='English',
        interests=['travel', 'music', 'anime'],
        personality=[5, 5, 1, 4, 5],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 28],
        preferred_salary_range=[6754, 12203],
        preferred_language='any',
        preferred_interests=['travel', 'reading'],
        preferred_personality=[3, 3, 5, 5, 4],
        preferred_height_range=[170, 182],
    ),
    User(
        name='Guo',
        age=19,
        gender='female',
        height=168,
        location='KL',
        salary=7583,
        language='English',
        interests=['travel', 'music', 'anime'],
        personality=[4, 5, 1, 5, 5],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 28],
        preferred_salary_range=[6564, 12203],
        preferred_language='any',
        preferred_interests=['travel', 'reading'],
        preferred_personality=[3, 3, 5, 5, 4],
        preferred_height_range=[168, 180],
    ),
    User(
        name='Insert',
        age=28,
        gender='female',
        height=173,
        location='Penang',
        salary=5526,
        language='English',
        interests=['tech', 'sports', 'travel'],
        personality=[2, 3, 2, 4, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5878, 10866],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[4, 4, 1, 2, 2],
        preferred_height_range=[170, 183],
    ),
    User(
        name='Joyce',
        age=32,
        gender='female',
        height=157,
        location='Penang',
        salary=5485,
        language='English',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4384, 9591],
        preferred_language='English',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[157, 173],
    ),
    User(
        name='Huang Zi Tao',
        age=29,  
        gender='female',
        height=158, 
        location='Penang',
        salary=6956, 
        language='English',
        interests=['reading', 'travel','cooking'],
        personality=[3, 2, 2, 4, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[5456, 8678],
        preferred_language='Chinese',
        preferred_interests=['music','sports'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[160, 175],
     ),
     User(
        name='Zhi Huan',
        age=25,
        gender='female',
        height=168,
        location='KL',
        salary=5013,
        language='English',
        interests=['cooking', 'sports', 'anime'],
        personality=[5, 5, 3, 3, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3927, 6766],
        preferred_language='any',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[2, 1, 5, 3, 2],
        preferred_height_range=[170, 183],
    ), 
    User(
        name='Pure',
        age=23,
        gender='female',
        height=156,
        location='Selangor',
        salary=6456,
        language='English',
        interests=['travel', 'tech', 'anime'],
        personality=[3, 2, 4, 3, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[24, 27],
        preferred_salary_range=[3341, 6060],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 5, 5, 3, 2],
        preferred_height_range=[160, 173],
    ),
    User(
        name='We Jie',
        age=28,
        gender='female',
        height=172,
        location='Penang',
        salary=5875,
        language='English',
        interests=['tech', 'sports', 'travel'],
        personality=[2, 2, 2, 4, 2],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5878, 10866],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[4, 4, 1, 2, 2],
        preferred_height_range=[172, 185],
    ),
    User(
        name='Zen Fan Ci',
        age=21,
        gender='female',
        height=174, 
        location='Selangor',
        salary=7845, 
        language='English',
        interests=['sports', 'food','anime'],
        personality=[4, 2, 2, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 28],
        preferred_salary_range=[7489, 11578],
        preferred_language='English',
        preferred_interests=['reading', 'anime'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[170, 185],
    ),
]