from matching_engine.user_model import User

female_Malay = [   
    User(
        name='Mia',
        age=30,
        gender='female',
        height=157,
        location='Ipoh',
        salary=4241,
        language='Malay',
        interests=['gaming', 'sports', 'cooking'],
        personality=[2, 4, 1, 1, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 31],
        preferred_salary_range=[3709, 4892],
        preferred_language='Malay',
        preferred_interests=['reading', 'cooking'],
        preferred_personality=[4, 2, 1, 3, 3],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Ryan',
        age=25,
        gender='female',
        height=159,
        location='KL',
        salary=6312,
        language='Malay',
        interests=['tech', 'anime', 'gaming'],
        personality=[4, 2, 4, 5, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4323, 8515],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[1, 3, 5, 3, 2],
        preferred_height_range=[161, 176],
    ),
    User(
        name='Alya Rahman',
        age=22,
        gender='female',
        height=171,
        location='Johor',
        salary=6145,
        language='Malay',
        interests=['movies', 'music'],
        personality=[2, 1, 4, 2, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 26],
        preferred_salary_range=[5967, 7678],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[171, 183],
    ),
    User(
        name='Wendy',
        age=35,
        gender='female',
        height=159,
        location='Johor',
        salary=6684,
        language='Malay',
        interests=['cooking', 'gaming', 'music'],
        personality=[2, 2, 4, 5, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[30, 43],
        preferred_salary_range=[3167, 6775],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[4, 5, 2, 5, 1],
        preferred_height_range=[160, 178],
    ),
    User(
        name='Aiden',
        age=33,
        gender='female',
        height=173,
        location='Penang',
        salary=5535,
        language='Malay',
        interests=['movies', 'travel', 'tech'],
        personality=[2, 3, 3, 5, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[27, 39],
        preferred_salary_range=[5622, 9968],
        preferred_language='Malay',
        preferred_interests=['cooking', 'travel'],
        preferred_personality=[1, 3, 5, 4, 4],
        preferred_height_range=[175, 185],
    ),
   User(
        name='Liam',
        age=24,
        gender='female',
        height=155,
        location='KL',
        salary=4521,
        language='Malay',
        interests=['music', 'sports', 'movies'],
        personality=[1, 1, 4, 5, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 26],
        preferred_salary_range=[3366, 5312],
        preferred_language='any',
        preferred_interests=['tech', 'sports'],
        preferred_personality=[2, 1, 4, 1, 5],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Quinn',
        age=20,
        gender='female',
        height=170,
        location='Johor',
        salary=4235,
        language='Malay',
        interests=['gaming', 'cooking', 'movies'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[19, 26],
        preferred_salary_range=[4568, 8579],
        preferred_language='any',
        preferred_interests=['cooking', 'reading'],
        preferred_personality=[3, 3, 1, 5, 5],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Umar',
        age=31,
        gender='female',
        height=157,
        location='Ipoh',
        salary=5960,
        language='Malay',
        interests=['movies', 'gaming', 'cooking'],
        personality=[1, 3, 4, 3, 1],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[23, 35],
        preferred_salary_range=[4189, 13297],
        preferred_language='Malay',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 2, 5, 4, 1],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Chen Yi Xun',
        age=24,
        gender='female',
        height=170,
        location='Selangor',
        salary=8978,
        language='Malay',
        interests=['fitness', 'gaming','cooking'],
        personality=[5, 1, 5, 3, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 30],
        preferred_salary_range=[8756, 12472],
        preferred_language='English',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[174, 185],
    ),
    User(
        name='Zhou Chuan Xiong',
        age=27,
        gender='female',
        height=174,
        location='Penang',
        salary=8876,
        language='Malay',
        interests=['food', 'travel','yoga'],
        personality=[3, 2, 3, 4, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[24, 30],
        preferred_salary_range=[7345, 9898],
        preferred_language='Malay',
        preferred_interests=['anime','yoga'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Hua Hua',
        age=24,
        gender='female',
        height=172,
        location='Selangor',
        salary=9778,
        language='Malay',
        interests=['music', 'cooking', 'fitness'],
        personality=[1, 4, 3, 2, 4],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[5373, 9724],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[4, 1, 4, 4, 2],
        preferred_height_range=[172, 184],
    ),
    User(
        name='Jade',
        age=23,
        gender='female',
        height=156,
        location='Penang',
        salary=5276,
        language='Malay',
        interests=['music', 'movies', 'anime'],
        personality=[4, 3, 4, 4, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[4047, 8628],
        preferred_language='Malay',
        preferred_interests=['anime', 'cooking'],
        preferred_personality=[3, 5, 3, 1, 4],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Nina',
        age=26,
        gender='female',
        height=173,
        location='Ipoh',
        salary=6813,
        language='Malay',
        interests=['reading', 'gaming', 'movies'],
        personality=[2, 3, 2, 3, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 30],
        preferred_salary_range=[6893, 13360],
        preferred_language='Malay',
        preferred_interests=['tech', 'gaming'],
        preferred_personality=[5, 1, 1, 2, 1],
        preferred_height_range=[164, 178],
    ),
    User(
        name='Nadia Aziz',
        age=23,
        gender='female',
        height=168,
        location='Johor',
        salary=6134,
        language='Malay',
        interests=['music', 'reading', 'movies'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 28],
        preferred_salary_range=[5845, 8345],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 181],
    ),
    User(
        name='Sasha',
        age=22,
        gender='female',
        height=169,
        location='KL',
        salary=5010,
        language='Malay',
        interests=['fitness', 'cooking', 'gaming'],
        personality=[1, 1, 5, 3, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[4079, 9359],
        preferred_language='Malay',
        preferred_interests=['travel', 'anime'],
        preferred_personality=[3, 2, 2, 4, 5],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Vivian',
        age=30,
        gender='female',
        height=157,
        location='Ipoh',
        salary=6549,
        language='Malay',
        interests=['music', 'reading', 'sports'],
        personality=[4, 3, 2, 5, 4],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 27],
        preferred_salary_range=[5295, 11442],
        preferred_language='Malay',
        preferred_interests=['tech', 'sports'],
        preferred_personality=[2, 3, 3, 3, 1],
        preferred_height_range=[163, 184],
    ),
    User(
        name='Xin xin',
        age=21,
        gender='female',
        height=167,
        location='Penang',
        salary=4887,
        language='Malay',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 3, 4, 5, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4996, 7662],
        preferred_language='Malay',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 3, 4, 3],
        preferred_height_range=[167, 185],
    ),
    User(
        name='Derek',
        age=19,
        gender='female',
        height=168,
        location='Selangor',
        salary=5917,
        language='Malay',
        interests=['tech', 'anime', 'music'],
        personality=[4, 3, 1, 4, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4585, 9698],
        preferred_language='any',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[4, 3, 3, 5, 1],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Logan',
        age=24,
        gender='female',
        height=169,
        location='Johor',
        salary=6894,
        language='Malay',
        interests=['fitness', 'cooking', 'reading'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5525, 10829],
        preferred_language='Malay',
        preferred_interests=['gaming', 'cooking'],
        preferred_personality=[1, 1, 4, 5, 2],
        preferred_height_range=[170, 184],
    ),
     User(
        name='Gura',
        age=24,
        gender='female',
        height=150,
        location='Kuala Lumpur',
        salary=6894,
        language='Malay',
        interests=['singing', 'streaming', 'reading'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5525, 10829],
        preferred_language='Malay',
        preferred_interests=['gaming', 'cooking'],
        preferred_personality=[1, 1, 4, 5, 2],
        preferred_height_range=[170, 184],
    ),
     User(
        name='Amelia',
        age=25,
        gender='female',
        height=160,
        location='Penang',
        salary=6894,
        language='Malay',
        interests=['dancing', 'cooking', 'gaming'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5525, 10829],
        preferred_language='Malay',
        preferred_interests=['singing', 'streaming'],
        preferred_personality=[1, 1, 4, 5, 2],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Lan Lao',
        age=25,
        gender='female',
        height=172,
        location='Selangor',
        salary=9465,
        language='Malay',
        interests=['fitness', 'music', 'gaming'],
        personality=[4, 1, 5, 3, 2],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 29],
        preferred_salary_range=[8456, 13673],
        preferred_language='English',
        preferred_interests=['fitness','movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[173, 182],
    ),
    User(
        name='Wayne',
        age=36,
        gender='female',
        height=164,
        location='Penang',
        salary=6390,
        language='Malay',
        interests=['fitness', 'travel', 'sports'],
        personality=[3, 4, 1, 3, 1],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 39],
        preferred_salary_range=[5329, 9312],
        preferred_language='Malay',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 4, 4, 5, 3],
        preferred_height_range=[170, 183],
    ),
    User(
        name='Dui Zhang',
        age=25,
        gender='female',
        height=178,
        location='KL',
        salary=9187,
        language='Malay',
        interests=['reading', 'music','anime'],
        personality=[3, 2, 3, 4, 2],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[20, 28],
        preferred_salary_range=[8876, 9598],
        preferred_language='Malay',
        preferred_interests=['anime','food'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 185],
    ),
    User(
        name='Syahirah Omar',
        age=25,
        gender='female',
        height=162,
        location='Melaka',
        salary=6312,
        language='Malay',
        interests=['travel', 'music'],
        personality=[3, 2, 3, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6123, 7890],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[161, 181],
),

    User(
        name='Emil',
        age=22,
        gender='female',
        height=160,
        location='KL',
        salary=6528,
        language='Malay',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 32],
        preferred_salary_range=[4074, 8810],
        preferred_language='Malay',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 1, 1, 4, 4],
        preferred_height_range=[161, 179],
    ),
    User(
        name='Gordon',
        age=19,
        gender='female',
        height=175,
        location='KL',
        salary=9511,
        language='Malay',
        interests=['fitness', 'music', 'sports'],
        personality=[2, 4, 4, 2, 3],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[19, 25],
        preferred_salary_range=[5384, 12442],
        preferred_language='Malay',
        preferred_interests=['gaming', 'anime'],
        preferred_personality=[4, 3, 4, 2, 4],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Relly',
        age=24,
        gender='female',
        height=158,
        location='Penang',
        salary=3685,
        language='Malay',
        interests=['sports', 'tech', 'anime'],
        personality=[3, 4, 5, 5, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3250, 7721],
        preferred_language='any',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[2, 1, 1, 4, 5],
        preferred_height_range=[162, 178],
    ),
    User(
        name='Eve',
        age=30,
        gender='female',
        height=176,
        location='Ipoh',
        salary=6961,
        language='Malay',
        interests=['anime', 'cooking', 'tech'],
        personality=[4, 2, 4, 1, 4],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[25, 32],
        preferred_salary_range=[3835, 5538],
        preferred_language='Malay',
        preferred_interests=['tech', 'gaming'],
        preferred_personality=[5, 3, 4, 4, 5],
        preferred_height_range=[155, 184],
    ),
     User(
        name='Xuan',
        age=25,
        gender='female',
        height=159,
        location='KL',
        salary=6312,
        language='Malay',
        interests=['tech', 'anime', 'gaming'],
        personality=[4, 2, 4, 5, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4563, 8785],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[1, 3, 4, 3, 2],
        preferred_height_range=[160, 176],
    ),
    User(
        name='Yasmin',
        age=23,
        gender='female',
        height=170,
        location='Johor',
        salary=5406,
        language='Malay',
        interests=['anime', 'travel', 'movies'],
        personality=[3, 1, 2, 2, 3],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[3127, 5968],
        preferred_language='Malay',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[2, 4, 5, 4, 1],
        preferred_height_range=[175, 186],
    ),
     User(
        name='Bule',
        age=30,
        gender='female',
        height=161,
        location='KL',
        salary=3770,
        language='Malay',
        interests=['music', 'travel', 'cooking'],
        personality=[4, 2, 1, 2, 3],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[22, 30],
        preferred_salary_range=[3014, 7677],
        preferred_language='Malay',
        preferred_interests=['travel', 'cooking'],
        preferred_personality=[5, 1, 4, 4, 3],
        preferred_height_range=[166, 179],
    ),
    User(
        name='Monica',
        age=22,
        gender='female',
        height=158,
        location='Ipoh',
        salary=5887,
        language='Malay',
        interests=['cooking', 'tech', 'gaming'],
        personality=[1, 3, 4, 5, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3146, 4805],
        preferred_language='Malay',
        preferred_interests=['reading', 'travel'],
        preferred_personality=[4, 1, 3, 2, 3],
        preferred_height_range=[169, 176],
    ),
    User(
        name='Monday',
        age=23,
        gender='female',
        height=157,
        location='Ipoh',
        salary=5887,
        language='Malay',
        interests=['cooking', 'tech', 'gaming'],
        personality=[1, 3, 4, 5, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3146, 7805],
        preferred_language='Malay',
        preferred_interests=['reading', 'travel'],
        preferred_personality=[4, 1, 3, 2, 3],
        preferred_height_range=[169, 176],
    ),
    User(
        name='Ain Nabila',
        age=27,
        gender='female',
        height=174,  
        location='Selangor',
        salary=6767,  
        language='Malay',
        interests=['sports', 'food'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6234, 7567],
        preferred_language='Chinese',
        preferred_interests=['reading', 'anime'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 184],
    ),
    User(
        name='Wang Yu Zhou',
        age=24,
        gender='female',
        height=171,
        location='Ipoh',
        salary=8687,
        language='Malay',
        interests=['anime', 'gaming', 'reading'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[7500, 9500],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 174],
    ),  
    User(
        name='Li Fan',
        age=27,
        gender='female',
        height=168,
        location='KL',
        salary=9845,
        language='Malay',
        interests=['gaming', 'travel','music'],
        personality=[4, 2, 4, 4, 2],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[8734, 14623],
        preferred_language='Malay',
        preferred_interests=['fitness','music'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Ji Shou',
        age=21,
        gender='female',
        height=168,
        location='KL',
        salary=7567,
        language='Malay',
        interests=['travel', 'music', 'anime'],
        personality=[5, 5, 1, 5, 5],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 28],
        preferred_salary_range=[6986, 12203],
        preferred_language='any',
        preferred_interests=['travel', 'reading'],
        preferred_personality=[3, 3, 5, 5, 4],
        preferred_height_range=[170, 178],
    ),
    User(
        name='Alina',
        age=21,
        gender='female',
        height=159,
        location='KL',
        salary=7124,
        language='Malay',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 32],
        preferred_salary_range=[4234, 8810],
        preferred_language='Malay',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 1, 1, 4, 4],
        preferred_height_range=[161, 180],
    ),
    User(
        name='Aimee',
        age=23,
        gender='female',
        height=158,
        location='KL',
        salary=6528,
        language='Malay',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 32],
        preferred_salary_range=[4376, 8810],
        preferred_language='Malay',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 1, 1, 4, 4],
        preferred_height_range=[161, 178],
    ),
    User(
        name='Carrei',
        age=25,
        gender='female',
        height=157,
        location='Penang',
        salary=4166,
        language='Malay',
        interests=['sports', 'tech', 'anime'],
        personality=[3, 4, 5, 4, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3250, 7721],
        preferred_language='Malay',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[2, 1, 3, 4, 5],
        preferred_height_range=[162, 179],
    ),
    User(
        name='White',
        age=25,
        gender='female',
        height=159,
        location='KL',
        salary=6812,
        language='Malay',
        interests=['tech', 'anime', 'gaming'],
        personality=[4, 2, 4, 5, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4895, 8515],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[1, 3, 4, 3, 2],
        preferred_height_range=[160,176],
    ),
    User(
        name='Zack',
        age=27,
        gender='female',
        height=162,
        location='Johor',
        salary=8925,
        language='Malay',
        interests=['tech', 'music', 'sports'],
        personality=[3, 4, 4, 5, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 30],
        preferred_salary_range=[5922, 12935],
        preferred_language='Malay',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[2, 4, 1, 4, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Friday',
        age=22,
        gender='female',
        height=157,
        location='Ipoh',
        salary=5967,
        language='Malay',
        interests=['cooking', 'tech', 'gaming'],
        personality=[1, 3, 4, 4, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 35],
        preferred_salary_range=[3146, 8805],
        preferred_language='Malay',
        preferred_interests=['reading', 'travel'],
        preferred_personality=[4, 1, 3, 2, 3],
        preferred_height_range=[169, 175],
    ),
    User(
        name='Noah',
        age=21,
        gender='female',
        height=159,
        location='Johor',
        salary=4663,
        language='Malay',
        interests=['sports', 'music', 'anime'],
        personality=[3, 2, 2, 1, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 28],
        preferred_salary_range=[3827, 6532],
        preferred_language='Malay',
        preferred_interests=['cooking', 'sports'],
        preferred_personality=[2, 4, 3, 2, 3],
        preferred_height_range=[165, 181],
    ),
    User(
        name='Xiao Hua',
        age=24,
        gender='female',
        height=168,
        location='Johor',
        salary=6894,
        language='Malay',
        interests=['fitness', 'cooking', 'reading'],
        personality=[5, 3, 2, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5863, 10829],
        preferred_language='Malay',
        preferred_interests=['gaming', 'cooking'],
        preferred_personality=[2, 1, 4, 5, 2],
        preferred_height_range=[170, 182],
    ),
    User(
        name='Ellie',
        age=24,
        gender='female',
        height=154,
        location='Penang',
        salary=3785,
        language='Malay',
        interests=['sports', 'tech', 'anime'],
        personality=[3, 4, 5, 5, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 29],
        preferred_salary_range=[3250, 7721],
        preferred_language='any',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[2, 1, 1, 4, 5],
        preferred_height_range=[162, 176],
    ),
    User(
        name='Zhong Zi Xuan',
        age=22,
        gender='female',
        height=170,
        location='Ipoh',
        salary=8734,
        language='Malay',
        interests=['anime', 'reading','food'],
        personality=[4, 1, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[21, 27],
        preferred_salary_range=[6543, 9347],
        preferred_language='English',
        preferred_interests=['sports', 'food'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Hana Zulkifli',
        age=29,  
        gender='female',
        height=158, 
        location='Penang',
        salary=6900, 
        language='Malay',
        interests=['reading', 'travel'],
        personality=[3, 2, 2, 4, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[23, 31],
        preferred_salary_range=[5000, 8000],
        preferred_language='Chinese',
        preferred_interests=['music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[161, 175],
    ),
    User(
        name='Sun Yan Zi',
        age=29,
        gender='female',
        height=165,
        location='Penang',
        salary=8800,
        language='Malay',
        interests=['reading', 'fitness','travel'],
        personality=[3, 2, 3, 2, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 31],
        preferred_salary_range=[7734, 9587],
        preferred_language='Malay',
        preferred_interests=['gaming'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Pen',
        age=30,
        gender='female',
        height=173,
        location='Ipoh',
        salary=6961,
        language='Malay',
        interests=['anime', 'cooking', 'tech'],
        personality=[4, 2, 4, 1, 4],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[25, 32],
        preferred_salary_range=[3456, 6538],
        preferred_language='Malay',
        preferred_interests=['tech', 'gaming'],
        preferred_personality=[5, 3, 4, 4, 5],
        preferred_height_range=[155, 183],
    ),  
    User(
        name='Jump',
        age=27,
        gender='female',
        height=162,
        location='Johor',
        salary=8875,
        language='Malay',
        interests=['tech', 'music', 'sports'],
        personality=[3, 4, 4, 5, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 30],
        preferred_salary_range=[5672, 12935],
        preferred_language='any',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[2, 4, 1, 4, 2],
        preferred_height_range=[168, 185],
    ),
     User(
        name='Apple',
        age=30,
        gender='female',
        height=160,
        location='KL',
        salary=3470,
        language='Malay',
        interests=['music', 'travel', 'cooking'],
        personality=[4, 2, 1, 2, 3],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[22, 30],
        preferred_salary_range=[3124, 7617],
        preferred_language='any',
        preferred_interests=['travel', 'cooking'],
        preferred_personality=[5, 1, 3, 4, 3],
        preferred_height_range=[168, 179],
    ),
 User(
        name='Lily',
        age=24,
        gender='female',
        height=168,
        location='Johor',
        salary=6765,
        language='Malay',
        interests=['fitness', 'cooking', 'reading'],
        personality=[5, 3, 1, 4, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5525, 11829],
        preferred_language='any',
        preferred_interests=['gaming', 'cooking'],
        preferred_personality=[1, 1, 4, 5, 2],
        preferred_height_range=[170, 182],
    ),
     User(
        name='Sun Yu',
        age=23,
        gender='female',
        height=164,
        location='Ipoh',
        salary=6677,
        language='Malay',
        interests=['gaming', 'sports', 'cooking'],
        personality=[2, 3, 1, 2, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 31],
        preferred_salary_range=[5678, 9898],
        preferred_language='Malay',
        preferred_interests=['reading', 'cooking'],
        preferred_personality=[4, 2, 1, 3, 3],
        preferred_height_range=[165, 183],
    ),
]