from matching_engine.user_model import User

female_Chinese = [

    User(
        name='Henry',
        age=29,
        gender='female',
        height=163,
        location='KL',
        salary=13069,
        language='Chinese',
        interests=['gaming', 'reading', 'anime'],
        personality=[4, 2, 1, 3, 2],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[20, 33],
        preferred_salary_range=[9148, 12563],
        preferred_language='any',
        preferred_interests=['tech', 'music'],
        preferred_personality=[3, 4, 1, 3, 4],
        preferred_height_range=[164, 185],
    ),
    User(
        name='Chen Lin',
        age=22,
        gender='female',
        height=170,
        location='Johor',
        salary=5932,
        language='Chinese',
        interests=['movies', 'music'],
        personality=[2, 1, 4, 2, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 25],
        preferred_salary_range=[6732, 7521],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[173, 183],
),
    User(
        name='Chen Xin Lan',
        age=24,
        gender='female',
        height=170,
        location='Selangor',
        salary=8756,
        language='Chinese',
        interests=['fitness', 'gaming','travel'],
        personality=[5, 2, 5, 3, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 28],
        preferred_salary_range=[8340, 12456],
        preferred_language='English',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Paul',
        age=30,
        gender='female',
        height=167,
        location='Ipoh',
        salary=4793,
        language='Chinese',
        interests=['travel', 'reading', 'anime'],
        personality=[2, 4, 1, 3, 5],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[22, 26],
        preferred_salary_range=[4610, 7617],
        preferred_language='Chinese',
        preferred_interests=['fitness', 'cooking'],
        preferred_personality=[3, 2, 1, 1, 3],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Queenie',
        age=24,
        gender='female',
        height=164,
        location='Penang',
        salary=6923,
        language='Chinese',
        interests=['music', 'gaming', 'reading'],
        personality=[5, 4, 2, 5, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 28],
        preferred_salary_range=[3575, 11178],
        preferred_language='Chinese',
        preferred_interests=['sports', 'gaming'],
        preferred_personality=[3, 2, 4, 1, 5],
        preferred_height_range=[164, 180],
    ),
    User(
        name='Ethan',
        age=25,
        gender='female',
        height=156,
        location='Penang',
        salary=5133,
        language='Chinese',
        interests=['movies', 'reading', 'travel'],
        personality=[5, 1, 2, 3, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[23, 30],
        preferred_salary_range=[3761, 7526],
        preferred_language='Chinese',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[5, 1, 4, 2, 1],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Hai Mian',
        age=23,
        gender='female',
        height=154,
        location='Selangor',
        salary=6343,
        language='Chinese',
        interests=['travel', 'tech', 'anime'],
        personality=[3, 2, 4, 3, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[24, 27],
        preferred_salary_range=[3771, 6060],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 5, 5, 3, 2],
        preferred_height_range=[158, 174],
    ),
    User(
        name='Wang Shu',
        age=23,
        gender='female',
        height=168,
        location='Johor',
        salary=6465,
        language='Chinese',
        interests=['music', 'reading', 'movies'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 28],
        preferred_salary_range=[5456, 8854],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 180],
),

   User(
        name='Ivy',
        age=30,
        gender='female',
        height=166,
        location='Ipoh',
        salary=5013,
        language='Chinese',
        interests=['fitness', 'gaming', 'reading'],
        personality=[2, 1, 5, 1, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 31],
        preferred_salary_range=[3946, 5903],
        preferred_language='Chinese',
        preferred_interests=['sports', 'tech'],
        preferred_personality=[5, 3, 4, 1, 1],
        preferred_height_range=[170, 185],
    ),
   User(
        name='Chen Yue',
        age=24,
        gender='female',
        height=165,
        location='Ipoh',
        salary=6834,
        language='Chinese',
        interests=['reading', 'cooking','fitness'],
        personality=[4, 2, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[5978, 8123],
        preferred_language='Malay',
        preferred_interests=['gaming', 'sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[160, 174],
    ),
   User(
        name='Zhang Wei Shan',
        age=26,
        gender='female',
        height=172,
        location='Selangor',
        salary=9236,
        language='Chinese',
        interests=['fitness', 'music', 'gaming'],
        personality=[4, 1, 5, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 30],
        preferred_salary_range=[8234, 11267],
        preferred_language='English',
        preferred_interests=['fitness', 'cooking'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[172, 180],
    ),
    User(
        name='Tina',
        age=24,
        gender='female',
        height=155,
        location='Selangor',
        salary=5332,
        language='Chinese',
        interests=['movies', 'gaming', 'sports'],
        personality=[5, 4, 1, 2, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 30],
        preferred_salary_range=[3745, 9343],
        preferred_language='any',
        preferred_interests=['anime', 'gaming'],
        preferred_personality=[2, 4, 3, 1, 2],
        preferred_height_range=[160, 177],
    ),
    User(
        name='Zhao',
        age=24,
        gender='female',
        height=172,
        location='Selangor',
        salary=9778,
        language='Chinese',
        interests=['music', 'cooking', 'fitness'],
        personality=[1, 4, 3, 2, 4],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[5762, 10024],
        preferred_language='any',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[4, 1, 4, 4, 2],
        preferred_height_range=[175, 185],
    ),
    User(
        name='Yu Weijie',
        age=21,
        gender='female',
        height=155,
        location='KL',
        salary=6726,
        language='Chinese',
        interests=['cooking', 'travel', 'sports'],
        personality=[3, 1, 3, 5, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 29],
        preferred_salary_range=[5632, 13202],
        preferred_language='Chinese',
        preferred_interests=['movies', 'cooking'],
        preferred_personality=[1, 1, 2, 5, 1],
        preferred_height_range=[160, 170],
    ),
    User(
        name='Ricky',
        age=23,
        gender='female',
        height=164,
        location='KL',
        salary=4284,
        language='Chinese',
        interests=['reading', 'fitness', 'cooking'],
        personality=[4, 1, 2, 4, 4],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[20, 33],
        preferred_salary_range=[4635, 7840],
        preferred_language='Chinese',
        preferred_interests=['sports', 'fitness'],
        preferred_personality=[5, 4, 1, 1, 4],
        preferred_height_range=[165, 176],
    ),
    User(
        name='Chloe',
        age=21,
        gender='female',
        height=167,
        location='Penang',
        salary=4097,
        language='Chinese',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 4, 4, 5, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4816, 7522],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 3, 3, 3],
        preferred_height_range=[167, 185],
    ),
    User(
        name='Lin Xin Yi',
        age=26,
        gender='female',
        height=168,
        location='Ipoh',
        salary=7156,
        language='Chinese',
        interests=['reading', 'music', 'cooking'],
        personality=[4, 3, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[5789, 8967],
        preferred_language='Malay',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[160, 180],
    ),
    User(
        name='Wu Xin Yi',
        age=25,
        gender='female',
        height=172,
        location='Penang',
        salary=8778,
        language='Chinese',
        interests=['movies', 'food','anime'],
        personality=[3, 3, 4, 3, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 31],
        preferred_salary_range=[8567, 11345],
        preferred_language='Chinese',
        preferred_interests=['sports','cooking'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 181],
    ),  
    User(
        name='Lin Xiu',
        age=26,
        gender='female',
        height=159,
        location='Melaka',
        salary=6300,
        language='Chinese',
        interests=['travel', 'music'],
        personality=[3, 2, 3, 2, 4],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6123, 8764],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[161, 178],
),

    User(
        name='Guan Guan',
        age=25,
        gender='female',
        height=165,
        location='Penang',
        salary=4097,
        language='Chinese',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 4, 4, 5, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4996, 7982],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 3, 4, 3],
        preferred_height_range=[167, 183],
    ),
    User(
        name='Li Jia Lin',
        age=27,
        gender='female',
        height=168,
        location='KL',
        salary=8786,
        language='Chinese',
        interests=['gaming', 'travel','fitness'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[23, 30],
        preferred_salary_range=[7347, 9585],
        preferred_language='any',
        preferred_interests=['fitness','movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 183],
   ),
   User(
        name='Harvey',
        age=30,
        gender='female',
        height=174,
        location='KL',
        salary=4389,
        language='Chinese',
        interests=['music', 'tech', 'travel'],
        personality=[4, 3, 1, 3, 4],
        preferred_gender='male',
        preferred_location='Johor',
        preferred_age_range=[24, 28],
        preferred_salary_range=[4890, 9947],
        preferred_language='Chinese',
        preferred_interests=['music', 'movies'],
        preferred_personality=[5, 5, 3, 3, 3],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Jonah',
        age=29,
        gender='female',
        height=160,
        location='Penang',
        salary=4795,
        language='Chinese',
        interests=['movies', 'reading', 'sports'],
        personality=[2, 1, 4, 1, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[24, 29],
        preferred_salary_range=[3699, 8740],
        preferred_language='Chinese',
        preferred_interests=['movies', 'cooking'],
        preferred_personality=[3, 5, 4, 5, 3],
        preferred_height_range=[164, 179],
    ),
    User(
        name='Kara',
        age=22,
        gender='female',
        height=165,
        location='Johor',
        salary=5387,
        language='Chinese',
        interests=['music', 'movies', 'cooking'],
        personality=[4, 3, 4, 5, 2],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 29],
        preferred_salary_range=[4142, 10972],
        preferred_language='any',
        preferred_interests=['travel', 'movies'],
        preferred_personality=[1, 2, 2, 5, 2],
        preferred_height_range=[164, 174],
    ),
    User(
        name='Ron',
        age=24,
        gender='female',
        height=163,
        location='Selangor',
        salary=9509,
        language='Chinese',
        interests=['travel', 'sports', 'movies'],
        personality=[4, 4, 3, 1, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[21, 28],
        preferred_salary_range=[8745, 11847],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[4, 5, 1, 2, 3],
        preferred_height_range=[165, 177],
    ),
    User(
        name='Valerie',
        age=33,
        gender='female',
        height=157,
        location='Penang',
        salary=5201,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4010, 9591],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[158, 173],
    ),
    User(
        name='Zhou Mei',
        age=25,
        gender='female',
        height=174, 
        location='Selangor',
        salary=6700,  
        language='Chinese',
        interests=['food', 'sports'],
        personality=[4, 3, 3, 3, 3],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[6234, 8764],
        preferred_language='Chinese',
        preferred_interests=['reading', 'gaming'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 180],
    ),

    User(
        name='Qing',
        age=29,
        gender='female',
        height=164,
        location='KL',
        salary=12349,
        language='Chinese',
        interests=['gaming', 'reading', 'anime'],
        personality=[4, 2, 1, 3, 2],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[20, 33],
        preferred_salary_range=[8148, 11563],
        preferred_language='any',
        preferred_interests=['tech', 'music'],
        preferred_personality=[3, 4, 1, 3, 4],
        preferred_height_range=[164, 185],
    ),
    User(
        name='Bella',
        age=30,
        gender='female',
        height=161,
        location='KL',
        salary=3270,
        language='Chinese',
        interests=['music', 'travel', 'cooking'],
        personality=[4, 2, 1, 2, 3],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[22, 30],
        preferred_salary_range=[3014, 7617],
        preferred_language='any',
        preferred_interests=['travel', 'cooking'],
        preferred_personality=[5, 1, 4, 4, 3],
        preferred_height_range=[168, 179],
    ),
    User(
        name='Hua Zai',
        age=28,
        gender='female',
        height=170,
        location='Johor',
        salary=6834,
        language='Chinese',
        interests=['travel', 'cooking','gaming'],
        personality=[3, 3, 1, 2, 4],
        preferred_gender='any',
        preferred_location='KL',
        preferred_age_range=[25, 32],
        preferred_salary_range=[6798, 8456],
        preferred_language='any',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[165, 182],
    ),
    User(
        name='Zhao Rui',
        age=25,
        gender='female',
        height=172,
        location='KL',
        salary=9978,
        language='Chinese',
        interests=['reading', 'travel','food'],
        personality=[3, 2, 4, 3, 2],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[23, 29],
        preferred_salary_range=[7453, 10676],
        preferred_language='any',
        preferred_interests=['anime','food'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 185],
    ),
    User(
        name='Iion',
        age=30,
        gender='female',
        height=167,
        location='Ipoh',
        salary=5993,
        language='Chinese',
        interests=['fitness', 'gaming', 'reading'],
        personality=[2, 1, 5, 1, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 31],
        preferred_salary_range=[3946, 5903],
        preferred_language='Chinese',
        preferred_interests=['sports', 'tech'],
        preferred_personality=[5, 3, 4, 1, 1],
        preferred_height_range=[169, 185],
    ),
    User(
        name='Hao Ren',
        age=29,
        gender='female',
        height=167,
        location='Ipoh',
        salary=5773,
        language='Chinese',
        interests=['fitness', 'gaming', 'reading'],
        personality=[2, 1, 5, 1, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 31],
        preferred_salary_range=[4566, 5983],
        preferred_language='Chinese',
        preferred_interests=['sports', 'tech'],
        preferred_personality=[5, 2, 4, 1, 1],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Wang Yi Xia',
        age=29,
        gender='female',
        height=165,
        location='Johor',
        salary=7543,
        language='Chinese',
        interests=['reading', 'yoga','cooking'],
        personality=[4, 3, 3, 3, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[25, 31],
        preferred_salary_range=[7743, 11456],
        preferred_language='Chinese',
        preferred_interests=['fitness','gaming'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Jasper',
        age=22,
        gender='female',
        height=158,
        location='Penang',
        salary=6715,
        language='Chinese',
        interests=['tech', 'gaming', 'reading'],
        personality=[1, 1, 4, 4, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 29],
        preferred_salary_range=[3618, 6200],
        preferred_language='any',
        preferred_interests=['travel', 'cooking'],
        preferred_personality=[1, 2, 2, 4, 4],
        preferred_height_range=[165, 178],
    ),
    User(
        name='Ai Ni',
        age=20,
        gender='female',
        height=166,
        location='KL',
        salary=7993,
        language='Chinese',
        interests=['travel', 'music', 'anime'],
        personality=[5, 5, 1, 5, 5],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[20, 28],
        preferred_salary_range=[6984, 12203],
        preferred_language='any',
        preferred_interests=['travel', 'reading'],
        preferred_personality=[3, 3, 5, 5, 4],
        preferred_height_range=[169, 180],
    ),  
    User(
        name='QQ',
        age=29,
        gender='female',
        height=175,
        location='Penang',
        salary=5526,
        language='Chinese',
        interests=['tech', 'sports', 'travel'],
        personality=[2, 2, 2, 4, 1],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5875, 10866],
        preferred_language='Chinese',
        preferred_interests=['travel', 'music'],
        preferred_personality=[4, 4, 1, 2, 3],
        preferred_height_range=[172, 185],
    ),
    User(
        name='Chue',
        age=22,
        gender='female',
        height=168,
        location='Penang',
        salary=4097,
        language='Chinese',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 4, 4, 5, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4964, 7522],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 2, 3, 3],
        preferred_height_range=[167, 185],
    ),
    User(
        name='Tan Hui',
        age=28,  
        gender='female',
        height=161, 
        location='Johor',
        salary=5475,
        language='Chinese',
        interests=['reading', 'travel'],
        personality=[3, 2, 2, 4, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[5000, 8000],
        preferred_language='Chinese',
        preferred_interests=['music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Carlson',
        age=32,
        gender='female',
        height=156,
        location='Penang',
        salary=5201,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4834, 9591],
        preferred_language='Chinese',
        preferred_interests=['trvel', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[159, 173],
    ),
User(
        name='Payne',
        age=32,
        gender='female',
        height=159,
        location='Penang',
        salary=5901,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4010, 8691],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[159, 172],
    ),
    User(
        name='Wang Fei',
        age=29,
        gender='female',
        height=162,
        location='Penang',
        salary=8547,
        language='Chinese',
        interests=['reading', 'travel','fitness'],
        personality=[3, 3, 2, 3, 3],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[25, 32],
        preferred_salary_range=[5467, 7890],
        preferred_language='Chinese',
        preferred_interests=['gaming','cooking'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[161, 182],
    ),
    User(
        name='Lillie',
        age=33,
        gender='female',
        height=156,
        location='Penang',
        salary=5701,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4310, 9591],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[159, 173],
    ),
    User(
        name='Ailsa',
        age=23,
        gender='female',
        height=162,
        location='KL',
        salary=6528,
        language='Chinese',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 32],
        preferred_salary_range=[4823, 8810],
        preferred_language='Chinese',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 2, 1, 4, 4],
        preferred_height_range=[163, 179],
    ),
    User(
        name='Li Mei Xuan',
        age=24,
        gender='female',
        height=174,
        location='Ipoh',
        salary=8556,
        language='Chinese',
        interests=['anime', 'cooking', 'reading'],
        personality=[4, 2, 3, 3, 2],
        preferred_gender='any',
        preferred_location='Selangor',
        preferred_age_range=[22, 30],
        preferred_salary_range=[7587, 9598],
        preferred_language='English',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[170, 185],
    ),
    User(
        name='Amy',
        age=22,
        gender='female',
        height=163,
        location='KL',
        salary=6928,
        language='Chinese',
        interests=['music', 'reading', 'travel'],
        personality=[4, 5, 2, 1, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[23, 32],
        preferred_salary_range=[4074, 8810],
        preferred_language='Chinese',
        preferred_interests=['movies', 'gaming'],
        preferred_personality=[1, 1, 1, 4, 4],
        preferred_height_range=[162, 179],
    ),
    User(
        name='Chen',
        age=29,
        gender='female',
        height=161,
        location='KL',
        salary=11069,
        language='Chinese',
        interests=['gaming', 'reading', 'anime'],
        personality=[4, 2, 1, 3, 2],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[20, 33],
        preferred_salary_range=[8148, 10563],
        preferred_language='any',
        preferred_interests=['tech', 'music'],
        preferred_personality=[3, 4, 1, 3, 4],
        preferred_height_range=[164, 183],
    ),
    User(
        name='Hair',
        age=27,
        gender='female',
        height=163,
        location='Johor',
        salary=9925,
        language='Chinese',
        interests=['tech', 'music', 'sports'],
        personality=[3, 4, 4, 5, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 30],
        preferred_salary_range=[5876, 12935],
        preferred_language='Chinese',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[2, 3, 1, 4, 2],
        preferred_height_range=[170, 184],
    ),
    User(
        name='Da Hao Ren',
        age=31,
        gender='female',
        height=164,
        location='Ipoh',
        salary=5013,
        language='Chinese',
        interests=['fitness', 'gaming', 'reading'],
        personality=[2, 1, 4, 1, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 31],
        preferred_salary_range=[3946, 5453],
        preferred_language='Chinese',
        preferred_interests=['sports', 'tech'],
        preferred_personality=[5, 3, 4, 1, 1],
        preferred_height_range=[168, 185],
    ),
    User(
        name='Tan Hui',
        age=28,        
        gender='female',
        height=158, 
        location='Johor',
        salary=5200,
        language='Chinese',
        interests=['reading', 'travel','sport'],
        personality=[3, 2, 2, 4, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[5465, 8764],
        preferred_language='English',
        preferred_interests=['music,reading'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[160, 175],
    ),

    User(
        name='Xin Guan',
        age=21,
        gender='female',
        height=166,
        location='Penang',
        salary=4097,
        language='Chinese',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 4, 4, 5, 3],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4996, 7522],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 3, 4, 3],
        preferred_height_range=[167, 185],
    ),
    User(
        name='Mann',
        age=32,
        gender='female',
        height=156,
        location='Penang',
        salary=5201,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4238, 9591],
        preferred_language='any',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[1, 4, 5, 3, 1],
        preferred_height_range=[159, 173],
    ),
    User(
        name='Elsa',
        age=24,
        gender='female',
        height=156,
        location='Penang',
        salary=4399,
        language='Chinese',
        interests=['sports', 'tech', 'anime'],
        personality=[3, 4, 5, 5, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[22, 29],
        preferred_salary_range=[4078, 7721],
        preferred_language='any',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[2, 1, 1, 4, 5],
        preferred_height_range=[160, 178],
    ),
    User(
        name='Action',
        age=27,
        gender='female',
        height=164,
        location='Johor',
        salary=8925,
        language='Chinese',
        interests=['tech', 'music', 'sports'],
        personality=[3, 4, 4, 5, 4],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[20, 30],
        preferred_salary_range=[5922, 12468],
        preferred_language='Chinese',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[2, 4, 1, 4, 2],
        preferred_height_range=[170, 183],
    ),
    User(
        name='Chen Yu Liang',
        age=22,
        gender='female',
        height=171,
        location='Ipoh',
        salary=7956,
        language='Chinese',
        interests=['reading', 'anime','sports'],
        personality=[4, 1, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[21, 28],
        preferred_salary_range=[7245, 9674],
        preferred_language='English',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 174],
    ),

    User(
        name='Very Hao Ren',
        age=30,
        gender='female',
        height=167,
        location='Ipoh',
        salary=5563,
        language='Chinese',
        interests=['fitness', 'gaming', 'reading'],
        personality=[2, 1, 5, 1, 4],
        preferred_gender='male',
        preferred_location='Penang',
        preferred_age_range=[25, 31],
        preferred_salary_range=[3946, 5093],
        preferred_language='Chinese',
        preferred_interests=['sports', 'tech'],
        preferred_personality=[5, 3, 4, 1, 1],
        preferred_height_range=[170, 183],
    ),
    User(
        name='Wilson',
        age=33,
        gender='female',
        height=158,
        location='Penang',
        salary=5201,
        language='Chinese',
        interests=['anime', 'fitness', 'sports'],
        personality=[2, 4, 3, 5, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[23, 36],
        preferred_salary_range=[4872, 9591],
        preferred_language='any',
        preferred_interests=['gaming', 'travel'],
        preferred_personality=[1, 3, 5, 3, 1],
        preferred_height_range=[158, 170],
    ),
]