from matching_engine.user_model import User

male_English = [

    User(
        name='Thai',
        age=29,
        gender='male',
        height=181,
        location='KL',
        salary=6530,
        language='English',
        interests=['reading', 'anime', 'cooking'],
        personality=[5, 5, 2, 2, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 35],
        preferred_salary_range=[3459, 5895],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[4, 3, 2, 2, 1],
        preferred_height_range=[162, 173],
    ),
    User(
        name='Hazel',
        age=27,
        gender='male',
        height=181,
        location='Selangor',
        salary=6348,
        language='English',
        interests=['anime', 'cooking', 'travel'],
        personality=[3, 2, 3, 2, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[21, 26],
        preferred_salary_range=[4183, 6743],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[2, 2, 4, 4, 1],
        preferred_height_range=[159, 174],
    ),
    User(
        name='Wang Hai Yang',
        age=24,
        gender='male',
        height=178,
        location='Ipoh',
        salary=8965,
        language='English',
        interests=['reading', 'anime', 'sports'],
        personality=[4, 1, 3, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[6789, 9587],
        preferred_language='English',
        preferred_interests=['anime', 'food'],
        preferred_personality=[4, 1, 2, 3, 2],
        preferred_height_range=[164, 175],
   ),
    User(
        name='Huang Zon Ze',
        age=24,
        gender='male',
        height=180,
        location='Ipoh',
        salary=8976,
        language='English',
        interests=['reading', 'cooking','sports'],
        personality=[4, 2, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[5678, 8765],
        preferred_language='Malay',
        preferred_interests=['gaming', 'sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[160, 169],
    ),
    User(
        name='Wen Hao',
        age=19,
        gender='male',
        height=166,
        location='Penang',
        salary=6475,
        language='English',
        interests=['music', 'tech', 'fitness'],
        personality=[2, 1, 5, 5, 1],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 26],
        preferred_salary_range=[3924, 7426],
        preferred_language='any',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[4, 1, 5, 5, 2],
        preferred_height_range=[159, 172],
    ),
    User(
        name='Zara',
        age=21,
        gender='male',
        height=183,
        location='KL',
        salary=5650,
        language='English',
        interests=['sports', 'cooking', 'travel'],
        personality=[2, 1, 3, 2, 3],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3918, 7838],
        preferred_language='English',
        preferred_interests=['music', 'cooking'],
        preferred_personality=[4, 2, 3, 2, 2],
        preferred_height_range=[159, 173],
    ),
    User(
        name='Wang Lei',
        age=30,
        gender='male',
        height=169,
        location='KL',
        salary=6324,
        language='English',
        interests=['travel', 'sports', 'music'],
        personality=[5, 2, 3, 3, 2],
        preferred_gender='male',
        preferred_location='any',
        preferred_age_range=[22, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[3, 1, 3, 3, 5],
        preferred_height_range=[169, 179],
    ),
    User(
        name='Ke Kun',
        age=22,
        gender='male',
        height=164,
        location='Ipoh',
        salary=4696,
        language='English',
        interests=['fitness', 'cooking', 'movies'],
        personality=[3, 1, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 30],
        preferred_salary_range=[3962, 6260],
        preferred_language='English',
        preferred_interests=['tech', 'gaming'],
        preferred_personality=[5, 1, 5, 3, 1],
        preferred_height_range=[155, 165],
    ),
     User(
        name='Hello',
        age=24,
        gender='male',
        height=178,
        location='Selangor',
        salary=8554,
        language='English',
        interests=['gaming', 'fitness', 'sports'],
        personality=[5, 2, 2, 2, 1],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4986, 8953],
        preferred_language='English',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[5, 3, 2, 1, 5],
        preferred_height_range=[158, 176],
    ),
    User(
        name='Qin Hao',
        age=25,
        gender='male',
        height=178,
        location='Ipoh',
        salary=8976,
        language='English',
        interests=['reading', 'music', 'cooking'],
        personality=[4, 2, 2, 3, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[23, 30],
        preferred_salary_range=[6567, 8465],
        preferred_language='Malay',
        preferred_interests=['sports', 'music'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[161, 168],
    ),
    User(
        name='Mason',
        age=30,
        gender='male',
        height=172,
        location='Ipoh',
        salary=7198,
        language='English',
        interests=['reading', 'movies', 'fitness'],
        personality=[2, 1, 1, 5, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 27],
        preferred_salary_range=[3049, 7985],
        preferred_language='any',
        preferred_interests=['cooking', 'gaming'],
        preferred_personality=[5, 3, 1, 2, 4],
        preferred_height_range=[159, 174],
    ),
    User(
        name='Paula',
        age=23,
        gender='male',
        height=181,
        location='KL',
        salary=6176,
        language='English',
        interests=['gaming', 'travel', 'reading'],
        personality=[5, 2, 2, 4, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 32],
        preferred_salary_range=[4757, 8459],
        preferred_language='English',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 4, 4, 1, 4],
        preferred_height_range=[164, 171],
    ),
    User(
        name='AK',
        age=25,
        gender='male',
        height=162,
        location='KL',
        salary=6982,
        language='English',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 2, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4267, 7170],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 3, 1, 1],
        preferred_height_range=[155, 170],
    ),
    User(
        name='Li Bai',
        age=28,
        gender='male',
        height=169,
        location='KL',
        salary=6734,
        language='English',
        interests=['reading', 'sports', 'travel'],
        personality=[5, 1, 3, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='Chinese',
        preferred_interests=['movies', 'reading'],
        preferred_personality=[4, 1, 3, 3, 5],
        preferred_height_range=[169, 177],
    ),
    User(
        name='Lin Ke Ke',
        age=25,
        gender='male',
        height=175,
        location='Ipoh',
        salary=8789,
        language='English',
        interests=['anime', 'reading','sports'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[22, 29],
        preferred_salary_range=[7587, 12832],
        preferred_language='English',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Felix',
        age=21,
        gender='male',
        height=163,
        location='Ipoh',
        salary=6683,
        language='English',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4893, 6253],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 1, 4, 2, 3],
        preferred_height_range=[156, 163],
    ),
    User(
        name='Da Mao',
        age=22,
        gender='male',
        height=163,
        location='Ipoh',
        salary=6873,
        language='English',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4893, 6253],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 1, 4, 2, 3],
        preferred_height_range=[158, 163],
    ),
    User(
        name='Neil',
        age=23,
        gender='male',
        height=163,
        location='Selangor',
        salary=11024,
        language='English',
        interests=['fitness', 'movies', 'cooking'],
        personality=[4, 2, 1, 4, 5],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 28],
        preferred_salary_range=[5675, 8326],
        preferred_language='any',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[3, 3, 2, 2, 1],
        preferred_height_range=[155, 172],
    ),
    User(
        name='Preston',
        age=22,
        gender='male',
        height=179,
        location='Johor',
        salary=11879,
        language='English',
        interests=['travel', 'tech', 'music'],
        personality=[3, 3, 4, 1, 3],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4707, 7212],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 5, 5, 2, 3],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Zhang Wen Zhuo',
        age=27,
        gender='male',
        height=172,
        location='Johor',
        salary=7856,
        language='English',
        interests=['cooking', 'sports','travel'],
        personality=[3, 3, 1, 2, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[24, 30],
        preferred_salary_range=[7876, 9875],
        preferred_language='any',
        preferred_interests=['gaming', 'reading'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[159, 168],
),

    User(
        name='Trevor',
        age=21,
        gender='male',
        height=163,
        location='Selangor',
        salary=9687,
        language='English',
        interests=['reading', 'tech', 'cooking'],
        personality=[1, 2, 2, 5, 5],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[19, 28],
        preferred_salary_range=[5250, 8955],
        preferred_language='English',
        preferred_interests=['travel', 'sports'],
        preferred_personality=[5, 2, 4, 3, 1],
        preferred_height_range=[155, 165],
    ),
    User(
        name='Wang Yan',
        age=29,
        gender='male',
        height=173,
        location='KL',
        salary=5723,
        language='English',
        interests=['reading', 'sports', 'travel'],
        personality=[5, 1, 3, 3, 2],
        preferred_gender='any',
        preferred_location='KL',
        preferred_age_range=[23, 30],
        preferred_salary_range=[4893, 7654],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[3, 1, 3, 3, 5],
        preferred_height_range=[169, 179],
    ),
    User(
        name='Hazel-Rose',
        age=19,
        gender='male',
        height=165,
        location='Johor',
        salary=5901,
        language='English',
        interests=['cooking', 'reading', 'music'],
        personality=[2, 4, 1, 1, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4120, 7936],
        preferred_language='English',
        preferred_interests=['music', 'cooking'],
        preferred_personality=[5, 1, 1, 5, 3],
        preferred_height_range=[155, 170],
    ),
    User(
        name='Kian',
        age=22,
        gender='male',
        height=173,
        location='KL',
        salary=4517,
        language='English',
        interests=['movies', 'cooking', 'fitness'],
        personality=[2, 4, 4, 2, 5],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[23, 28],
        preferred_salary_range=[3012, 5653],
        preferred_language='English',
        preferred_interests=['anime', 'gaming'],
        preferred_personality=[3, 3, 1, 5, 5],
        preferred_height_range=[168, 174],
    ),
    User(
        name='Frank',
        age=28,
        gender='male',
        height=170,
        location='Ipoh',
        salary=5290,
        language='English',
        interests=['tech', 'anime', 'cooking'],
        personality=[1, 2, 3, 2, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3890, 6367],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[5, 3, 4, 2, 5],
        preferred_height_range=[164, 184],
    ),
    User(
        name='Olivia',
        age=21,
        gender='male',
        height=184,
        location='Ipoh',
        salary=4344,
        language='English',
        interests=['fitness', 'reading', 'gaming'],
        personality=[1, 1, 4, 3, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 28],
        preferred_salary_range=[3820, 5844],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[1, 5, 2, 3, 1],
        preferred_height_range=[165, 176],
    ),
    User(
        name='Yang  Qing',
        age=28,
        gender='male',
        height=169,
        location='KL',
        salary=5987,
        language='English',
        interests=['reading', 'sports', 'music'],
        personality=[5, 1, 3, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[3, 1, 3, 3, 5],
        preferred_height_range=[169, 179],
    ),
    User(
        name='Victor',
        age=29,
        gender='male',
        height=183,
        location='KL',
        salary=6030,
        language='English',
        interests=['reading', 'anime', 'cooking'],
        personality=[5, 5, 2, 2, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 35],
        preferred_salary_range=[3689, 5895],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[4, 3, 2, 2, 1],
        preferred_height_range=[162, 174],
    ),
    User(
        name='Jin',
        age=19,
        gender='male',
        height=164,
        location='Penang',
        salary=6396,
        language='English',
        interests=['music', 'tech', 'fitness'],
        personality=[2, 1, 5, 4, 1],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 26],
        preferred_salary_range=[3724, 7426],
        preferred_language='any',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[4, 1, 5, 5, 2],
        preferred_height_range=[159, 174],
    ),
    User(
        name='Xena',
        age=28,
        gender='male',
        height=182,
        location='Johor',
        salary=6585,
        language='English',
        interests=['movies', 'music', 'sports'],
        personality=[2, 1, 2, 2, 3],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[25, 32],
        preferred_salary_range=[4116, 9675],
        preferred_language='English',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[5, 2, 3, 3, 5],
        preferred_height_range=[156, 175],
    ),
    User(
        name='Luo Bin Han',
        age=30,
        gender='male',
        height=174,
        location='Selangor',
        salary=8100,
        language='English',
        interests=['reading', 'travel'],
        personality=[4, 3, 2, 4, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[25, 32],
        preferred_salary_range=[7498, 8789],
        preferred_language='English',
        preferred_interests=['sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[163, 174],
    ),
    User(
        name='Si Jie',
        age=23,
        gender='male',
        height=171,
        location='KL',
        salary=8798,
        language='English',
        interests=['anime', 'gaming','reading'],
        personality=[3, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[21, 26],
        preferred_salary_range=[7887, 9556],
        preferred_language='English',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 178],
    ), 
    User(
        name='George',
        age=25,
        gender='male',
        height=178,
        location='Selangor',
        salary=4744,
        language='English',
        interests=['cooking', 'travel', 'fitness'],
        personality=[4, 4, 5, 1, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 30],
        preferred_salary_range=[3470, 7791],
        preferred_language='any',
        preferred_interests=['travel', 'music'],
        preferred_personality=[1, 5, 1, 3, 2],
        preferred_height_range=[163, 177],
    ),
     User(
        name='Tan Tan',
        age=28,
        gender='male',
        height=176,
        location='Selangor',
        salary=8554,
        language='English',
        interests=['gaming', 'fitness', 'sports'],
        personality=[5, 2, 2, 2, 1],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4897, 8376],
        preferred_language='English',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[5, 3, 2, 1, 5],
        preferred_height_range=[157, 174],
    ),
    User(
        name='Paula',
        age=23,
        gender='male',
        height=182,
        location='KL',
        salary=6985,
        language='English',
        interests=['gaming', 'travel', 'reading'],
        personality=[5, 2, 2, 4, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 32],
        preferred_salary_range=[4767, 8459],
        preferred_language='English',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 4, 4, 1, 4],
        preferred_height_range=[165, 171],
    ),
    User(
        name='Fule',
        age=21,
        gender='male',
        height=163,
        location='Ipoh',
        salary=6783,
        language='English',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4993, 6763],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 2, 4, 2, 3],
        preferred_height_range=[155, 163],
    ),
    User(
        name='Yang Yi',
        age=26,
        gender='male',
        height=167,
        location='KL',
        salary=6024,
        language='English',
        interests=['travel', 'sports', 'music'],
        personality=[4, 1, 3, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[3, 1, 4, 3, 3],
        preferred_height_range=[169, 179],
    ),
    User(
        name='wine',
        age=21,
        gender='male',
        height=162,
        location='Ipoh',
        salary=6683,
        language='English',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4963, 6253],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 1, 4, 2, 3],
        preferred_height_range=[156, 163],
    ),
    User(
        name='Warner',
        age=23,
        gender='male',
        height=178,
        location='Johor',
        salary=11639,
        language='English',
        interests=['travel', 'tech', 'music'],
        personality=[3, 3, 4, 1, 3],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4387, 7472],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 5, 5, 2, 3],
        preferred_height_range=[166, 175],
    ),
    User(
        name='Nolan',
        age=25,
        gender='male',
        height=162,
        location='Ipoh',
        salary=7435,
        language='English',
        interests=['anime', 'fitness', 'tech'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3987, 6580],
        preferred_language='English',
        preferred_interests=['tech', 'reading'],
        preferred_personality=[2, 4, 2, 3, 4],
        preferred_height_range=[159, 164],
    ),
    User(
        name='Grenn',
        age=29,
        gender='male',
        height=184,
        location='KL',
        salary=6430,
        language='English',
        interests=['reading', 'anime', 'cooking'],
        personality=[5, 5, 2, 2, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 35],
        preferred_salary_range=[3689, 5895],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[4, 3, 2, 2, 1],
        preferred_height_range=[162, 175],
    ),
     User(
        name='Bing',
        age=20,
        gender='male',
        height=183,
        location='Johor',
        salary=4679,
        language='English',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3981, 5139],
        preferred_language='English',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[165, 174],
    ),
    User(
        name='Hannah',
        age=32,
        gender='male',
        height=165,
        location='Selangor',
        salary=3122,
        language='English',
        interests=['sports', 'anime', 'cooking'],
        personality=[3, 2, 3, 4, 2],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[22, 37],
        preferred_salary_range=[3275, 6612],
        preferred_language='English',
        preferred_interests=['travel', 'sports'],
        preferred_personality=[5, 2, 4, 3, 5],
        preferred_height_range=[159, 177],
    ),
    User(
        name='Ron Zu Er',
        age=27,
        gender='male',
        height=172,
        location='Penang',
        salary=7687,
        language='English',
        interests=['reading', 'travel','sports'],
        personality=[3, 3, 3, 3, 2],
        preferred_gender='any',
        preferred_location='KL',
        preferred_age_range=[24, 30],
        preferred_salary_range=[7023, 9837],
        preferred_language='English',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Lu Pen',
        age=24,
        gender='male',
        height=171,
        location='Ipoh',
        salary=5987,
        language='English',
        interests=['movies', 'travel', 'music'],
        personality=[4, 1, 3, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='English',
        preferred_interests=['movies', 'music'],
        preferred_personality=[3, 1, 4, 3, 5],
        preferred_height_range=[169, 179],
    ),
    User(
        name='Ian',
        age=28,
        gender='male',
        height=175,
        location='Selangor',
        salary=8554,
        language='English',
        interests=['gaming', 'fitness', 'sports'],
        personality=[5, 2, 2, 2, 1],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4887, 8376],
        preferred_language='English',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[5, 3, 2, 1, 5],
        preferred_height_range=[158, 174],
    ),
     User(
        name='June',
        age=25,
        gender='male',
        height=170,
        location='Selangor',
        salary=8664,
        language='English',
        interests=['gaming', 'fitness', 'sports'],
        personality=[5, 2, 2, 2, 1],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4887, 8376],
        preferred_language='English',
        preferred_interests=['reading', 'movies'],
        preferred_personality=[5, 3, 2, 1, 5],
        preferred_height_range=[158, 173],
    ),
   User(
        name='Glass',
        age=23,
        gender='male',
        height=183,
        location='KL',
        salary=5898,
        language='English',
        interests=['music', 'reading', 'anime'],
        personality=[4, 3, 2, 1, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 31],
        preferred_salary_range=[4982, 8758],
        preferred_language='English',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[1, 1, 3, 4, 4],
        preferred_height_range=[163, 175],
   ),
    User(
        name='Shift',
        age=23,
        gender='male',
        height=180,
        location='KL',
        salary=6986,
        language='English',
        interests=['gaming', 'travel', 'reading'],
        personality=[5, 2, 2, 4, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 32],
        preferred_salary_range=[4877, 8459],
        preferred_language='English',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 4, 4, 1, 4],
        preferred_height_range=[164, 172],
    ),
    User(
        name='Viou',
        age=21,
        gender='male',
        height=162,
        location='Ipoh',
        salary=6562,
        language='English',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4892, 6353],
        preferred_language='English',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 1, 4, 2, 3],
        preferred_height_range=[155, 163],
    ),
    User(
        name='Young',
        age=22,
        gender='male',
        height=180,
        location='Johor',
        salary=11879,
        language='English',
        interests=['travel', 'tech', 'music'],
        personality=[3, 4, 4, 1, 3],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4707, 7382],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 5, 5, 2, 3],
        preferred_height_range=[165, 174],
    ),
    User(
        name='Walter',
        age=19,
        gender='male',
        height=167,
        location='Johor',
        salary=3943,
        language='English',
        interests=['music', 'gaming', 'cooking'],
        personality=[1, 1, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3794, 7643],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[5, 4, 5, 5, 2],
        preferred_height_range=[155, 168],
    ),
User(
        name='Yang Rui',
        age=24,
        gender='male',
        height=169,
        location='Ipoh',
        salary=5987,
        language='English',
        interests=['movies', 'sports', 'music'],
        personality=[4, 1, 3, 3, 2],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 27],
        preferred_salary_range=[4893, 7654],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[3, 1, 4, 3, 5],
        preferred_height_range=[169, 179],
    ),
    User(
        name='Key',
        age=29,
        gender='male',
        height=185,
        location='KL',
        salary=6030,
        language='English',
        interests=['reading', 'anime', 'cooking'],
        personality=[5, 5, 2, 2, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 35],
        preferred_salary_range=[4689, 6895],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[4, 3, 2, 2, 1],
        preferred_height_range=[161, 174],
    ),
    User(
        name='Victory',
        age=32,
        gender='male',
        height=175,
        location='Selangor',
        salary=5493,
        language='English',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 39],
        preferred_salary_range=[4633, 7840],
        preferred_language='English',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[156, 171],
    ),
    User(
        name='Tanner',
        age=22,
        gender='male',
        height=177,
        location='Johor',
        salary=11879,
        language='English',
        interests=['travel', 'tech', 'music'],
        personality=[3, 3, 4, 1, 3],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4347, 7212],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 5, 5, 2, 3],
        preferred_height_range=[165, 176],
    ),
    User(
        name='Lin Yu Han',
        age=22,
        gender='male',
        height=181,
        location='Ipoh',
        salary=10982,
        language='English',
        interests=['fitness', 'cooking', 'movies'],
        personality=[3, 3, 2, 5, 3],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 30],
        preferred_salary_range=[6545, 9876],
        preferred_language='English',
        preferred_interests=['fitness', 'gaming'],
        preferred_personality=[5, 1, 5, 3, 1],
        preferred_height_range=[160, 175],
    ),
]