from matching_engine.user_model import User

male_Chinese = [
     User(
        name='Dylan',
        age=23,
        gender='male',
        height=173,
        location='Ipoh',
        salary=7382,
        language='Chinese',
        interests=['fitness', 'anime', 'tech'],
        personality=[3, 1, 2, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 25],
        preferred_salary_range=[3919, 5256],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[5, 1, 2, 2, 2],
        preferred_height_range=[157, 173],
    ),
    User(
        name='Huo Qiu Zi',
        age=23,
        gender='male',
        height=178,
        location='Ipoh',
        salary=8923,
        language='Chinese',
        interests=['reading', 'anime', 'sports'],
        personality=[3, 1, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[7000, 10000],
        preferred_language='English',
        preferred_interests=['anime', 'food'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Grace',
        age=27,
        gender='male',
        height=178,
        location='Johor',
        salary=6349,
        language='Chinese',
        interests=['cooking', 'anime', 'tech'],
        personality=[1, 5, 5, 2, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[3927, 6611],
        preferred_language='any',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 5, 1, 4, 3],
        preferred_height_range=[155, 185],
    ),
    User(
        name='Liu Zhi Tao',
        age=24,
        gender='male',
        height=181,
        location='Ipoh',
        salary=9453,
        language='Chinese',
        interests=['reading', 'cooking'],
        personality=[4, 2, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[5678, 8767],
        preferred_language='Malay',
        preferred_interests=['sports', 'gaming'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[158, 171],
),

    User(
        name='Isabel',
        age=26,
        gender='male',
        height=176,
        location='Johor',
        salary=7757,
        language='Chinese',
        interests=['movies', 'reading', 'travel'],
        personality=[4, 3, 3, 2, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4359, 6652],
        preferred_language='any',
        preferred_interests=['music', 'gaming'],
        preferred_personality=[3, 1, 5, 4, 5],
        preferred_height_range=[164, 172],
    ),
     User(
        name='Caleb',
        age=22,
        gender='male',
        height=168,
        location='KL',
        salary=6706,
        language='Chinese',
        interests=['travel', 'reading', 'sports'],
        personality=[1, 2, 2, 3, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[19, 29],
        preferred_salary_range=[4470, 7054],
        preferred_language='Chinese',
        preferred_interests=['anime', 'music'],
        preferred_personality=[5, 4, 5, 3, 1],
        preferred_height_range=[156, 169],
    ),
     User(
        name='Ophelia',
        age=29,
        gender='male',
        height=169,
        location='Penang',
        salary=5080,
        language='Chinese',
        interests=['tech', 'reading', 'fitness'],
        personality=[2, 4, 1, 2, 1],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[22, 26],
        preferred_salary_range=[3675, 5357],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'tech'],
        preferred_personality=[1, 1, 2, 4, 3],
        preferred_height_range=[155, 170],
    ),
     User(
        name='Vera',
        age=19,
        gender='male',
        height=165,
        location='Penang',
        salary=6396,
        language='Chinese',
        interests=['music', 'tech', 'fitness'],
        personality=[2, 1, 5, 5, 1],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[19, 26],
        preferred_salary_range=[3724, 7426],
        preferred_language='any',
        preferred_interests=['fitness', 'movies'],
        preferred_personality=[4, 1, 5, 5, 2],
        preferred_height_range=[159, 170],
    ),
     User(
        name='Will',
        age=21,
        gender='male',
        height=183,
        location='Ipoh',
        salary=13082,
        language='Chinese',
        interests=['cooking', 'music', 'sports'],
        personality=[4, 4, 5, 5, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 27],
        preferred_salary_range=[7380, 10684],
        preferred_language='Chinese',
        preferred_interests=['travel', 'fitness'],
        preferred_personality=[2, 2, 2, 1, 1],
        preferred_height_range=[163, 175],
    ),
     User(
        name='Zhen Chao',
        age=20,
        gender='male',
        height=185,
        location='Johor',
        salary=4564,
        language='Chinese',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3981, 5139],
        preferred_language='Chinese',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[165, 176],
    ),
     User(
         name='Zhang Ming',
         age=25,
         gender='male',
         height=173,
         location='Ipoh',
         salary=7890,
         language='Chinese',
         interests=['reading', 'music', 'cooking'],
         personality=[4, 3, 1, 3, 2],
         preferred_gender='female',
         preferred_location='Penang',
         preferred_age_range=[23, 30],
         preferred_salary_range=[6045, 9567],
         preferred_language='any',
         preferred_interests=['cooking','sports'],
         preferred_personality=[2, 3, 1, 2, 1],
         preferred_height_range=[165, 180],
    ),
    User(
        name='Laura',
        age=24,
        gender='male',
        height=180,
        location='KL',
        salary=5777,
        language='Chinese',
        interests=['music', 'reading', 'anime'],
        personality=[4, 3, 2, 1, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 31],
        preferred_salary_range=[4268, 8758],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[1, 1, 3, 4, 4],
        preferred_height_range=[162, 174],
    ),
     User(
        name='Hung Tao',
        age=23,
        gender='male',
        height=172,
        location='Ipoh',
        salary=7887,
        language='Chinese',
        interests=['fitness', 'anime', 'tech'],
        personality=[3, 1, 2, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 25],
        preferred_salary_range=[3819, 6256],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[5, 1, 2, 2, 2],
        preferred_height_range=[158, 174],
    ),
    User(
        name='Ipad',
        age=27,
        gender='male',
        height=174,
        location='Johor',
        salary=6569,
        language='Chinese',
        interests=['cooking', 'anime', 'tech'],
        personality=[1, 5, 5, 2, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4927, 6611],
        preferred_language='any',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 5, 1, 4, 3],
        preferred_height_range=[156, 185],
    ),
    User(
        name='Peter',
        age=21,
        gender='male',
        height=182,
        location='Penang',
        salary=5401,
        language='Chinese',
        interests=['reading', 'sports', 'music'],
        personality=[5, 3, 3, 5, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 31],
        preferred_salary_range=[3884, 9789],
        preferred_language='Chinese',
        preferred_interests=['music', 'sports'],
        preferred_personality=[3, 5, 5, 5, 5],
        preferred_height_range=[160, 170],
    ),
    User(
        name='Shi Jin',
        age=25,
        gender='male',
        height=175,
        location='Ipoh',
        salary=8576,
        language='Chinese',
        interests=['anime', 'reading','cooking'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[7634, 10234],
        preferred_language='English',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 180],
    ),
     User(
        name='Zhen Cha',
        age=21,
        gender='male',
        height=186,
        location='Johor',
        salary=4975,
        language='Chinese',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3981, 5459],
        preferred_language='Chinese',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[165, 176],
    ),
    User(
        name='Kevin',
        age=22,
        gender='male',
        height=160,
        location='Selangor',
        salary=5501,
        language='Chinses',
        interests=['anime', 'sports', 'music'],
        personality=[1, 1, 4, 3, 5],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[4858, 6213],
        preferred_language='Chinese',
        preferred_interests=['reading', 'cooking'],
        preferred_personality=[4, 1, 3, 5, 2],
        preferred_height_range=[155, 165],
    ),  
   User(
        name='Cap',
        age=24,
        gender='male',
        height=183,
        location='KL',
        salary=5857,
        language='Chinese',
        interests=['music', 'reading', 'anime'],
        personality=[4, 3, 2, 1, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 31],
        preferred_salary_range=[4962, 8758],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[1, 1, 3, 4, 4],
        preferred_height_range=[163, 174],
   ),
   User(
        name='Tyler',
        age=23,
        gender='male',
        height=183,
        location='KL',
        salary=6344,
        language='Chinese',
        interests=['reading', 'fitness', 'anime'],
        personality=[1, 3, 5, 4, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4859, 7518],
        preferred_language='Chinese',
        preferred_interests=['tech', 'anime'],
        preferred_personality=[5, 1, 5, 1, 5],
        preferred_height_range=[169, 175],
    ),
    User(
        name='Amber',
        age=23,
        gender='male',
        height=168,
        location='Penang',
        salary=5038,
        language='Chinese',
        interests=['gaming', 'tech', 'fitness'],
        personality=[2, 1, 4, 2, 4],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[21, 32],
        preferred_salary_range=[3979, 6584],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[3, 2, 1, 2, 4],
        preferred_height_range=[158, 170],
    ),
    User(
        name='Chen Zi Ang',
        age=27,
        gender='male',
        height=178,
        location='Johor',
        salary=7898,
        language='Chinese',
        interests=['cooking', 'sports','fitness'],
        personality=[3, 3, 1, 2, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 30],
        preferred_salary_range=[7234, 9678],
        preferred_language='any',
        preferred_interests=['gaming','cooking'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[159, 170],
    ),
    User(
        name='Eliza',
        age=24,
        gender='male',
        height=181,
        location='Johor',
        salary=6386,
        language='Chinese',
        interests=['reading', 'tech', 'sports'],
        personality=[4, 1, 3, 3, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[23, 32],
        preferred_salary_range=[5004, 7104],
        preferred_language='Chinese',
        preferred_interests=['movies', 'reading'],
        preferred_personality=[5, 3, 3, 1, 5],
        preferred_height_range=[158, 174],
    ),
    User(
        name='Isla',
        age=32,
        gender='male',
        height=174,
        location='Selangor',
        salary=5493,
        language='Chinese',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 39],
        preferred_salary_range=[4743, 7840],
        preferred_language='Chinese',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[156, 170],
    ),
    User(
        name='Xu Wei Yi',
        age=29,
        gender='male',
        height=165,
        location='Johor',
        salary=6123,
        language='Chinese',
        interests=['gaming', 'food','sports'],
        personality=[4, 2, 3, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[21, 31],
        preferred_salary_range=[5674, 10455],
        preferred_language='Chinese',
        preferred_interests=['movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[163, 182],
    ),
    User(
        name='Chen Zi',
        age=32,
        gender='male',
        height=175,
        location='Selangor',
        salary=5963,
        language='Chinese',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 39],
        preferred_salary_range=[4743, 7840],
        preferred_language='any',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[155, 171],
    ),
    User(
        name='Table',
        age=21,
        gender='male',
        height=164,
        location='Ipoh',
        salary=6683,
        language='Chinese',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4893, 6965],
        preferred_language='Chinese',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 2, 4, 2, 3],
        preferred_height_range=[157, 163],
    ),
    User(
        name='Olga',
        age=29,
        gender='male',
        height=177,
        location='Penang',
        salary=10064,
        language='Chinese',
        interests=['music', 'tech', 'movies'],
        personality=[3, 4, 1, 5, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 30],
        preferred_salary_range=[5414, 7807],
        preferred_language='any',
        preferred_interests=['gaming', 'fitness'],
        preferred_personality=[3, 4, 1, 2, 4],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Siena',
        age=22,
        gender='male',
        height=170,
        location='Johor',
        salary=13424,
        language='Chinese',
        interests=['music', 'movies', 'tech'],
        personality=[5, 3, 3, 2, 2],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[20, 28],
        preferred_salary_range=[5471, 8406],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[2, 2, 2, 3, 5],
        preferred_height_range=[157,170],
    ),
    User(
        name='Ula',
        age=27,
        gender='male',
        height=182,
        location='Ipoh',
        salary=8923,
        language='Chinese',
        interests=['fitness', 'sports', 'cooking'],
        personality=[1, 4, 4, 4, 1],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[21, 29],
        preferred_salary_range=[4621, 8780],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[1, 4, 5, 3, 4],
        preferred_height_range=[162, 176],
    ),
    User(
        name='Ximena',
        age=37,
        gender='male',
        height=170,
        location='Penang',
        salary=7437,
        language='Chinese',
        interests=['movies', 'sports', 'cooking'],
        personality=[4, 3, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[25, 39],
        preferred_salary_range=[4967, 8039],
        preferred_language='Chinese',
        preferred_interests=['travel', 'fitness'],
        preferred_personality=[5, 2, 5, 4, 5],
        preferred_height_range=[159, 170],
    ),
    User(
        name='Zoey',
        age=20,
        gender='male',
        height=174,
        location='Penang',
        salary=6342,
        language='Chinese',
        interests=['reading', 'music', 'sports'],
        personality=[4, 2, 3, 1, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[19, 26],
        preferred_salary_range=[3697, 6026],
        preferred_language='any',
        preferred_interests=['anime', 'tech'],
        preferred_personality=[5, 2, 1, 2, 4],
        preferred_height_range=[156, 174],
    ),
    User(
        name='Chen Zhen',
        age=24,
        gender='male',
        height=171,
        location='KL',
        salary=7976,
        language='Chinese',
        interests=['anime', 'cooking'],
        personality=[3, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[22, 27],
        preferred_salary_range=[7087, 9598],
        preferred_language='any',
        preferred_interests=['anime', 'sports'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Colin',
        age=22,
        gender='male',
        height=176,
        location='Selangor',
        salary=4121,
        language='Chinese',
        interests=['cooking', 'music', 'tech'],
        personality=[1, 5, 2, 2, 3],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[21, 30],
        preferred_salary_range=[3855, 5645],
        preferred_language='Chinese',
        preferred_interests=['travel', 'anime'],
        preferred_personality=[3, 3, 4, 4, 4],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Xuan Yi',
        age=23,
        gender='male',
        height=174,
        location='Ipoh',
        salary=7897,
        language='Chinese',
        interests=['fitness', 'anime', 'tech'],
        personality=[3, 1, 2, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 25],
        preferred_salary_range=[3919, 6256],
        preferred_language='Chinese',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[5, 1, 2, 2, 2],
        preferred_height_range=[157, 173],
    ),
    User(
        name='Logan',
        age=27,
        gender='male',
        height=179,
        location='Johor',
        salary=6789,
        language='Chinese',
        interests=['cooking', 'anime', 'tech'],
        personality=[1, 5, 5, 2, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[3457, 6561],
        preferred_language='Chinese',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 5, 1, 4, 3],
        preferred_height_range=[156, 184],
    ),
    User(
        name='Chen Long',
        age=27,
        gender='male',
        height=168,
        location='KL',
        salary=8785,
        language='Chinese',
        interests=['fitness', 'travel','music'],
        personality=[4, 2, 4, 4, 2],
        preferred_gender='any',
        preferred_location='Selangor',
        preferred_age_range=[22, 28],
        preferred_salary_range=[7686, 13457],
        preferred_language='any',
        preferred_interests=['fitness', 'cooking'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[168, 182],
   ),
    User(
        name='Karen',
        age=23,
        gender='male',
        height=180,
        location='Penang',
        salary=6230,
        language='Chinese',
        interests=['cooking', 'travel', 'tech'],
        personality=[1, 3, 5, 1, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[21, 27],
        preferred_salary_range=[4751, 6958],
        preferred_language='Chinese',
        preferred_interests=['travel', 'movies'],
        preferred_personality=[2, 5, 1, 4, 2],
        preferred_height_range=[159, 175],
    ),
    User(
        name='Wang Jie Yi',
        age=29,
        gender='male',
        height=164, 
        location='KL',
        salary=8178,
        language='Chinese',
        interests=['reading', 'travel','cooking'],
        personality=[4, 3, 2, 4, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 32],
        preferred_salary_range=[6234, 8776],
        preferred_language='Malay',
        preferred_interests=['gaming'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[159, 170],
    ),
    User(
        name='Xie',
        age=21,
        gender='male',
        height=181,
        location='Penang',
        salary=5401,
        language='Chinese',
        interests=['reading', 'sports', 'music'],
        personality=[5, 3, 3, 5, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 31],
        preferred_salary_range=[3674, 9789],
        preferred_language='any',
        preferred_interests=['music', 'sports'],
        preferred_personality=[3, 5, 5, 5, 5],
        preferred_height_range=[160, 173],
    ),
    User(
        name='Back',
        age=21,
        gender='male',
        height=183,
        location='Penang',
        salary=6401,
        language='Chinese',
        interests=['reading', 'sports', 'music'],
        personality=[5, 3, 3, 5, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 31],
        preferred_salary_range=[3884, 9789],
        preferred_language='Chinese',
        preferred_interests=['music', 'sports'],
        preferred_personality=[3, 5, 5, 5, 5],
        preferred_height_range=[160, 171],
    ),
     User(
        name='Shao',
        age=20,
        gender='male',
        height=186,
        location='Johor',
        salary=4354,
        language='Chinese',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3761, 5139],
        preferred_language='Chinese',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[164,176],
    ),
     User(
        name='Ye',
        age=21,
        gender='male',
        height=187,
        location='Johor',
        salary=4664,
        language='Chinese',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3981, 5139],
        preferred_language='Chinese',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[167, 176],
    ),
   User(
        name='Hi Hi',
        age=24,
        gender='male',
        height=182,
        location='KL',
        salary=5857,
        language='Chinese',
        interests=['music', 'reading', 'anime'],
        personality=[4, 3, 2, 1, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 31],
        preferred_salary_range=[4962, 8888],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[1, 1, 3, 4, 4],
        preferred_height_range=[163, 173],
   ),
    User(
        name='Orange',
        age=32,
        gender='male',
        height=174,
        location='Selangor',
        salary=5375,
        language='Chinese',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[26, 39],
        preferred_salary_range=[4273, 7840],
        preferred_language='Chinese',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[156, 173],
    ),
    User(
        name='Wang Bo',
        age=26,
        gender='male',
        height=180,
        location='Johor',
        salary=7776,
        language='Chinese',
        interests=['sports', 'music','reading'],
        personality=[3, 2, 3, 3, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[21, 30],
        preferred_salary_range=[7500, 9000],
        preferred_language='Chinese',
        preferred_interests=['sports','reading'],
        preferred_personality=[3, 2, 2, 3, 2],
        preferred_height_range=[165, 182],
    ),

    User(
        name='Steam',
        age=32,
        gender='male',
        height=172,
        location='Selangor',
        salary=5493,
        language='Chinese',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 38],
        preferred_salary_range=[4743, 7840],
        preferred_language='Chinese',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 3, 2, 5],
        preferred_height_range=[155, 170],
    ),
    User(
        name='Klein',
        age=22,
        gender='male',
        height=171,
        location='Johor',
        salary=13424,
        language='Chinese',
        interests=['music', 'movies', 'tech'],
        personality=[5, 3, 3, 2, 2],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[20, 28],
        preferred_salary_range=[5471, 9806],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[2, 2, 2, 3, 5],
        preferred_height_range=[157,169],
    ),
    User(
        name='Li Hao Wen',
        age=24,
        gender='male',
        height=174,
        location='Selangor',
        salary=8769,
        language='Chinese',
        interests=['gaming', 'reading','tech'],
        personality=[4, 2, 5, 3, 2],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 30],
        preferred_salary_range=[8675, 12352],
        preferred_language='any',
        preferred_interests=['fitness','cooking'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 182],
),

    User(
        name='Keith',
        age=25,
        gender='male',
        height=161,
        location='Ipoh',
        salary=7435,
        language='Chinese',
        interests=['anime', 'fitness', 'tech'],
        personality=[3, 1, 4, 1, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3779, 6580],
        preferred_language='Chinese',
        preferred_interests=['tech', 'reading'],
        preferred_personality=[2, 4, 2, 1, 4],
        preferred_height_range=[156, 165],
    ),
    User(
        name='Hnery',
        age=20,
        gender='male',
        height=167,
        location='Johor',
        salary=3903,
        language='Chinese',
        interests=['music', 'gaming', 'cooking'],
        personality=[1, 1, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3104, 6643],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[5, 4, 5, 4, 2],
        preferred_height_range=[155, 167],
    ),
   User(
        name='Lin',
        age=23,
        gender='male',
        height=180,
        location='Penang',
        salary=7230,
        language='Chinese',
        interests=['cooking', 'travel', 'tech'],
        personality=[1, 3, 5, 1, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[21, 27],
        preferred_salary_range=[4751, 8958],
        preferred_language='Chinese',
        preferred_interests=['travel', 'movies'],
        preferred_personality=[2, 5, 1, 4, 2],
        preferred_height_range=[158, 175],
    ),
     User(
        name='Huisan',
        age=20,
        gender='male',
        height=186,
        location='Johor',
        salary=4664,
        language='Chinese',
        interests=['reading', 'anime', 'tech'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[20, 45],
        preferred_salary_range=[3981, 5339],
        preferred_language='Chinese',
        preferred_interests=['tech', 'travel'],
        preferred_personality=[2, 5, 2, 2, 2],
        preferred_height_range=[165, 175],
    ),
   User(
        name='Cap',
        age=24,
        gender='male',
        height=182,
        location='KL',
        salary=5964,
        language='Chinese',
        interests=['music', 'reading', 'anime'],
        personality=[4, 3, 2, 1, 4],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[22, 31],
        preferred_salary_range=[4985, 8758],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[1, 1, 3, 4, 4],
        preferred_height_range=[163, 175],
   ),
    User(
        name='Dian',
        age=21,
        gender='male',
        height=166,
        location='Penang',
        salary=4963,
        language='Chinese',
        interests=['tech', 'fitness', 'anime'],
        personality=[1, 4, 4, 5, 3],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 30],
        preferred_salary_range=[4816, 7422],
        preferred_language='Chinese',
        preferred_interests=['cooking', 'fitness'],
        preferred_personality=[5, 1, 3, 4, 3],
        preferred_height_range=[167, 184],
    ),
    User(
        name='Xiao Mao',
        age=20,
        gender='male',
        height=163,
        location='Ipoh',
        salary=6964,
        language='Chinese',
        interests=['movies', 'sports', 'anime'],
        personality=[4, 3, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4893, 6253],
        preferred_language='Chinese',
        preferred_interests=['travel', 'music'],
        preferred_personality=[2, 1, 4, 2, 5],
        preferred_height_range=[155, 163],
    ),
    User(
        name='Steve',
        age=22,
        gender='male',
        height=172,
        location='Johor',
        salary=12354,
        language='Chinese',
        interests=['music', 'movies', 'tech'],
        personality=[5, 3, 3, 2, 2],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[20, 28],
        preferred_salary_range=[5471, 87506],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[2, 2, 2, 3, 5],
        preferred_height_range=[157,172],
    ),
    User(
        name='Jack',
        age=22,
        gender='male',
        height=169,
        location='Penang',
        salary=3393,
        language='Chinese',
        interests=['fitness', 'reading', 'music'],
        personality=[4, 2, 5, 4, 3],
        preferred_gender='male',
        preferred_location='KL',
        preferred_age_range=[21, 29],
        preferred_salary_range=[3875, 8285],
        preferred_language='any',
        preferred_interests=['reading', 'anime'],
        preferred_personality=[1, 4, 3, 1, 1],
        preferred_height_range=[164, 185],
    ),
    User(
        name='Zhao Tian Yu',
        age=23,
        gender='male',
        height=172,
        location='Selangor',
        salary=7654,
        language='Chinese',
        interests=['fitness', 'gaming','music'],
        personality=[5, 1, 5, 3, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[20, 28],
        preferred_salary_range=[7875, 11234],
        preferred_language='English',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Cola',
        age=23,
        gender='male',
        height=181,
        location='Penang',
        salary=6230,
        language='Chinese',
        interests=['cooking', 'travel', 'tech'],
        personality=[1, 3, 5, 1, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[21, 27],
        preferred_salary_range=[4751, 7958],
        preferred_language='Chinese',
        preferred_interests=['travel', 'movies'],
        preferred_personality=[2, 5, 1, 4, 2],
        preferred_height_range=[159, 178],
    ),
    User(
        name='Black',
        age=32,
        gender='male',
        height=173,
        location='Selangor',
        salary=5863,
        language='Chinese',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 2, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[26, 39],
        preferred_salary_range=[4743, 7840],
        preferred_language='any',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[156, 171],
    ),
        User(
        name='Liu Yin',
        age=21,
        gender='male',
        height=174,
        location='Ipoh', 
        salary=6964,
        language='Chinese',
        interests=['movies', 'sports', 'music'],
        personality=[4, 1, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[19, 27],
        preferred_salary_range=[4893, 6453],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[2, 1, 4, 2, 5],
        preferred_height_range=[160, 172],
    ),
]