from matching_engine.user_model import User

male_Malay = [

     User(
        name='Phone',
        age=28,
        gender='male',
        height=168,
        location='KL',
        salary=3122,
        language='Malay',
        interests=['sports', 'music', 'travel'],
        personality=[4, 3, 5, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 27],
        preferred_salary_range=[3374, 4896],
        preferred_language='any',
        preferred_interests=['cooking', 'tech'],
        preferred_personality=[4, 4, 2, 5, 4],
        preferred_height_range=[156, 168],
    ),
    User(
        name='Abel',
        age=26,
        gender='male',
        height=170,
        location='Penang',
        salary=4399,
        language='Malay',
        interests=['music', 'cooking', 'movies'],
        personality=[5, 2, 2, 1, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[21, 30],
        preferred_salary_range=[3904, 8473],
        preferred_language='Malay',
        preferred_interests=['gaming', 'anime'],
        preferred_personality=[5, 5, 2, 2, 1],
        preferred_height_range=[157, 174],
    ),
    User(
        name='Bianca',
        age=32,
        gender='male',
        height=166,
        location='Selangor',
        salary=5884,
        language='Malay',
        interests=['gaming', 'anime', 'tech'],
        personality=[5, 5, 1, 5, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 40],
        preferred_salary_range=[3266, 5233],
        preferred_language='any',
        preferred_interests=['music', 'cooking'],
        preferred_personality=[5, 3, 2, 4, 1],
        preferred_height_range=[155, 170],
    ),
    User(
        name='Xu Wei',
        age=23,
        gender='male',
        height=178,
        location='Ipoh',
        salary=10346,
        language='Malay',
        interests=['anime', 'reading','sports'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[20, 26],
        preferred_salary_range=[7023, 10234],
        preferred_language='English',
        preferred_interests=['sports', 'food'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 175],
    ),
User(
    name='Ren Jie',
        age=22,
        gender='male',
        height=171,
        location='Johor',
        salary=6100,
        language='Malay',
        interests=['movies', 'music', 'travel'],
        personality=[2, 1, 4, 2, 5],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 25],
        preferred_salary_range=[6634, 7500],
        preferred_language='Chinese',
        preferred_interests=['sports', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[171, 180],
    ),
    User(
        name='Xander',
        age=25,
        gender='male',
        height=162,
        location='KL',
        salary=6892,
        language='Malay',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 2, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4811, 7170],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 3, 1, 1],
        preferred_height_range=[155, 172],
    ),
    User(
        name='Ma Tian Hao',
        age=23,
        gender='male',
        height=176,
        location='Selangor',
        salary=9656,
        language='Malay',
        interests=['fitness', 'gaming','movies'],
        personality=[5, 2, 5, 3, 1],
        preferred_gender='male',
        preferred_location='Ipoh',
        preferred_age_range=[20, 28],
        preferred_salary_range=[7645,12347],
        preferred_language='English',
        preferred_interests=['cooking', 'movies'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[161, 183],
),

    User(
        name='Zion',
        age=29,
        gender='male',
        height=167,
        location='Ipoh',
        salary=5573,
        language='Malay',
        interests=['cooking', 'gaming', 'travel'],
        personality=[1, 2, 3, 4, 1],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[20, 27],
        preferred_salary_range=[3410, 7914],
        preferred_language='Malay',
        preferred_interests=['reading', 'sports'],
        preferred_personality=[3, 2, 1, 2, 4],
        preferred_height_range=[160, 167],
    ),
    User(
        name='Brent',
        age=22,
        gender='male',
        height=185,
        location='Selangor',
        salary=6600,
        language='Malay',
        interests=['cooking', 'tech', 'gaming'],
        personality=[2, 1, 2, 3, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 30],
        preferred_salary_range=[4513, 7175],
        preferred_language='Malay',
        preferred_interests=['anime', 'music'],
        preferred_personality=[4, 2, 4, 3, 4],
        preferred_height_range=[165, 174],
    ),
    User(
        name='Huang Bo',
        age=32, 
        gender='male',
        height=164,
        location='KL',
        salary=9345,
        language='Malay',
        interests=['food', 'yoga','anime'],
        personality=[5, 4, 2, 4, 3],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[28, 35],
        preferred_salary_range=[7685, 9874],
        preferred_language='Malay',
        preferred_interests=['reading','sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[165, 180],
    ),
    User(
        name='Gloria',
        age=20,
        gender='male',
        height=156,
        location='Johor',
        salary=6933,
        language='Malay',
        interests=['fitness', 'tech', 'anime'],
        personality=[3, 5, 1, 2, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[19, 28],
        preferred_salary_range=[3627, 7552],
        preferred_language='Malay',
        preferred_interests=['anime', 'travel'],
        preferred_personality=[4, 1, 5, 4, 3],
        preferred_height_range=[155, 160],
    ),
        User(
        name='Li Fen Chun',
        age=24,
        gender='male',
        height=176,
        location='Ipoh',
        salary=8467,
        language='Malay',
        interests=['anime', 'sports', 'reading'],
        personality=[4, 2, 4, 3, 2],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[21, 28],
        preferred_salary_range=[7123, 9987],
        preferred_language='any',
        preferred_interests=['food', 'anime'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Li Rui',
        age=24,
        gender='male',
        height=173,
        location='Melaka',
        salary=6450,
        language='Malay',
        interests=['music', 'reading'],
        personality=[2, 2, 4, 3, 4],
        preferred_gender='any',
        preferred_location='Ipoh',
        preferred_age_range=[21, 30],
        preferred_salary_range=[6500, 7500],
        preferred_language='Chinese',
        preferred_interests=['movies', 'sports'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[165, 179],
    ),
    User(
        name='Lloyd',
        age=23,
        gender='male',
        height=178,
        location='Johor',
        salary=11879,
        language='Malay',
        interests=['travel', 'tech', 'music'],
        personality=[3, 3, 4, 2, 3],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[20, 31],
        preferred_salary_range=[4867, 7212],
        preferred_language='any',
        preferred_interests=['music', 'reading'],
        preferred_personality=[5, 5, 5, 2, 3],
        preferred_height_range=[165, 175],
    ),
    User(
        name='Huang Xuan',
        age=25,
        gender='male',
        height=171,
        location='Selangor',
        salary=8900,
        language='Malay',
        interests=['fitness', 'music', 'gaming'],
        personality=[4, 1, 4, 3, 1],
        preferred_gender='male',
        preferred_location='Selangor',
        preferred_age_range=[22, 29],
        preferred_salary_range=[7564, 11678],
        preferred_language='any',
        preferred_interests=['movies', 'cooking'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[166, 185],
    ),
    User(
        name='Yosef',
        age=25,
        gender='male',
        height=180,
        location='Ipoh',
        salary=7055,
        language='Malay',
        interests=['cooking', 'reading', 'fitness'],
        personality=[1, 1, 1, 3, 1],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[21, 32],
        preferred_salary_range=[3483, 6568],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[2, 1, 1, 5, 4],
        preferred_height_range=[156, 175],
    ),
    User(
        name='Alvin',
        age=29,
        gender='male',
        height=184,
        location='Penang',
        salary=6856,
        language='Malay',
        interests=['cooking', 'music', 'tech'],
        personality=[3, 1, 2, 3, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[23, 26],
        preferred_salary_range=[3658, 7823],
        preferred_language='Malay',
        preferred_interests=['movies', 'travel'],
        preferred_personality=[2, 5, 3, 2, 4],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Hao Jian',
        age=26,
        gender='male',
        height=176,
        location='Johor',
        salary=6700,
        language='Malay',
        interests=['gaming', 'music'],
        personality=[3, 2, 3, 2, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 28],
        preferred_salary_range=[5374, 8799],
        preferred_language='Chinese',
        preferred_interests=['movies', 'music'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[160, 175],
    ), 
    User(
        name='Delilah',
        age=37,
        gender='male',
        height=179,
        location='Penang',
        salary=4741,
        language='Malay',
        interests=['reading', 'cooking', 'gaming'],
        personality=[5, 4, 4, 5, 1],
        preferred_gender='female',
        preferred_location='any',
        preferred_age_range=[25, 39],
        preferred_salary_range=[3814, 6229],
        preferred_language='any',
        preferred_interests=['fitness', 'reading'],
        preferred_personality=[2, 1, 1, 4, 4],
        preferred_height_range=[155, 173],
    ),
    User(
        name='Imran',
        age=21,
        gender='male',
        height=167,
        location='Johor',
        salary=3333,
        language='Malay',
        interests=['music', 'gaming', 'cooking'],
        personality=[1, 1, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3794, 6643],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[5, 4, 5, 5, 2],
        preferred_height_range=[155, 169],
    ),
    User(
        name='Yuan Quan',
        age=26,
        gender='male',
        height=169,
        location='Kuala Lumpur',
        salary=8876,
        language='Malay',
        interests=['gaming', 'travel','music'],
        personality=[4, 2, 4, 4, 2],
        preferred_gender='any',
        preferred_location='Selangor',
        preferred_age_range=[23, 31],
        preferred_salary_range=[8754, 12687],
        preferred_language='any',
        preferred_interests=['movies','cooking'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[165, 182],
    ),
    User(
        name='Sophia',
        age=28,
        gender='male',
        height=185,
        location='Penang',
        salary=6630,
        language='Malay',
        interests=['anime', 'music', 'gaming'],
        personality=[5, 3, 4, 1, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[22, 30],
        preferred_salary_range=[3707, 6907],
        preferred_language='Malay',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[1, 5, 1, 1, 5],
        preferred_height_range=[158, 174],
    ),
    User(
        name='Zhong Zi Xuan',
        age=24,
        gender='male',
        height=170,
        location='Ipoh',
        salary=7178,
        language='Malay',
        interests=['reading', 'cooking','sports'],
        personality=[4, 2, 1, 3, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 27],
        preferred_salary_range=[4567, 8578],
        preferred_language='Malay',
        preferred_interests=['gaming', 'sports'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[159, 170],
    ),
    User(
        name='Daphne',
        age=28,
        gender='male',
        height=167,
        location='KL',
        salary=3122,
        language='Malay',
        interests=['sports', 'music', 'travel'],
        personality=[4, 3, 5, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 27],
        preferred_salary_range=[3734, 4946],
        preferred_language='Malay',
        preferred_interests=['cooking', 'tech'],
        preferred_personality=[4, 4, 2, 5, 4],
        preferred_height_range=[156, 169],
    ),
    User(
        name='Lin Jun Jie',
        age=25,
        gender='male',
        height=172,
        location='Ipoh',
        salary=8898,
        language='Malay',
        interests=['reading', 'gaming','tech'],
        personality=[3, 2, 4, 3, 3],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[22, 30],
        preferred_salary_range=[7684, 9595],
        preferred_language='English',
        preferred_interests=['reading','tech'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[160, 175],
    ),
    User(
        name='Xin Xin',
        age=32,
        gender='male',
        height=165,
        location='Selangor',
        salary=5774,
        language='Malay',
        interests=['gaming', 'anime', 'tech'],
        personality=[5, 5, 1, 5, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[25, 40],
        preferred_salary_range=[3876, 5233],
        preferred_language='any',
        preferred_interests=['music', 'cooking'],
        preferred_personality=[5, 3, 2, 4, 1],
        preferred_height_range=[156, 170],
    ),
    User(
        name='Gou Ba',
        age=25,
        gender='male',
        height=162,
        location='KL',
        salary=7916,
        language='Malay',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 2, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4881, 7170],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 4, 1, 1],
        preferred_height_range=[156, 172],
    ),
    User(
        name='Xiao Shou',
        age=25,
        gender='male',
        height=163,
        location='KL',
        salary=6964,
        language='Malay',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 3, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4811, 7170],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 3, 1, 1],
        preferred_height_range=[156, 172],
    ),
    User(
        name='Iron Man',
        age=32,
        gender='male',
        height=174,
        location='Selangor',
        salary=5364,
        language='Malay',
        interests=['fitness', 'travel', 'movies'],
        personality=[1, 1, 2, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 39],
        preferred_salary_range=[4798, 7374],
        preferred_language='Malay',
        preferred_interests=['anime', 'reading'],
        preferred_personality=[2, 1, 2, 2, 5],
        preferred_height_range=[156, 170],
    ),
    User(
        name='Ethan',
        age=24,
        gender='male',
        height=181,
        location='Ipoh',
        salary=7455,
        language='Malay',
        interests=['cooking', 'reading', 'fitness'],
        personality=[1, 1, 1, 3, 1],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[21, 32],
        preferred_salary_range=[3483, 6568],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[2, 1, 1, 5, 4],
        preferred_height_range=[156, 176],
    ),
    User(
        name='Shi Jie',
        age=28,
        gender='male',
        height=177,
        location='Penang',
        salary=9145,
        language='Malay',
        interests=['reading', 'fitness','movies'],
        personality=[3, 2, 4, 3, 3],
        preferred_gender='female',
        preferred_location='Selangor',
        preferred_age_range=[25, 32],
        preferred_salary_range=[7000, 9500],
        preferred_language='Malay',
        preferred_interests=['gaming','fitness'],
        preferred_personality=[3, 3, 2, 5, 3],
        preferred_height_range=[177, 184],
    ),
    User(
        name='Son Ya Xuan',
        age=25,
        gender='male',
        height=175,
        location='Ipoh',
        salary=7550,
        language='Malay',
        interests=['reading', 'music', 'cooking'],
        personality=[4, 2, 2, 3, 3],
        preferred_gender='female',
        preferred_location='KL',
        preferred_age_range=[23, 28],
        preferred_salary_range=[6578, 9678],
        preferred_language='Malay',
        preferred_interests=['gaming','cooking'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[163, 169],
),

    User(
        name='Nelson',
        age=28,
        gender='male',
        height=179,
        location='Ipoh',
        salary=7374,
        language='Malay',
        interests=['cooking', 'reading', 'fitness'],
        personality=[1, 1, 1, 3, 1],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[21, 32],
        preferred_salary_range=[4356, 6568],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[2, 1, 1, 5, 4],
        preferred_height_range=[155, 175],
    ),
    User(
        name='He Shen',
        age=28,
        gender='male',
        height=165,
        location='KL',
        salary=7200,
        language='Malay',
        interests=['travel', 'anime'],
        personality=[4, 3, 2, 4, 3],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[22, 29],
        preferred_salary_range=[6000, 7500],
        preferred_language='Chinese',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[4, 1, 4, 3, 2],
        preferred_height_range=[163, 175],
    ), 
    User(
        name='Bella-Rae',
        age=24,
        gender='male',
        height=160,
        location='Ipoh',
        salary=7435,
        language='Malay',
        interests=['anime', 'fitness', 'tech'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[22, 29],
        preferred_salary_range=[3429, 6580],
        preferred_language='Malay',
        preferred_interests=['tech', 'reading'],
        preferred_personality=[2, 4, 2, 1, 4],
        preferred_height_range=[159, 165],
    ),
    User(
    name='Ma Liang',
        age=27,
        gender='male',
        height=180,
        location='Penang',
        salary=9034,
        language='Malay',
        interests=['music', 'reading','anime'],
        personality=[3, 2, 3, 4, 2],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[20, 35],
        preferred_salary_range=[7598, 10234],
        preferred_language='Malay',
        preferred_interests=['sports','music'],
        preferred_personality=[4, 2, 2, 3, 2],
        preferred_height_range=[165, 185],
    ),
    User(
        name='Albert',
        age=23,
        gender='male',
        height=171,
        location='Ipoh',
        salary=7987,
        language='Malay',
        interests=['anime', 'fitness', 'tech'],
        personality=[3, 1, 4, 2, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[22, 29],
        preferred_salary_range=[4029, 6580],
        preferred_language='Malay',
        preferred_interests=['tech', 'reading'],
        preferred_personality=[2, 4, 2, 1, 4],
        preferred_height_range=[159, 168],
    ),
    User(
        name='Spider',
        age=21,
        gender='male',
        height=168,
        location='Johor',
        salary=3973,
        language='Malay',
        interests=['music', 'gaming', 'cooking'],
        personality=[2, 1, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3794, 6443],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[5, 4, 3, 5, 2],
        preferred_height_range=[155, 170],
    ),
    User(
        name='Webb',
        age=21,
        gender='male',
        height=167,
        location='Johor',
        salary=3653,
        language='Malay',
        interests=['music', 'gaming', 'cooking'],
        personality=[2, 1, 5, 5, 4],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[3794, 6643],
        preferred_language='any',
        preferred_interests=['sports', 'anime'],
        preferred_personality=[5, 4, 5, 5, 2],
        preferred_height_range=[157, 167],
    ),
     User(
        name='Tian Tian',
        age=28,
        gender='male',
        height=166,
        location='KL',
        salary=4122,
        language='Malay',
        interests=['sports', 'music', 'travel'],
        personality=[4, 3, 5, 1, 5],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 27],
        preferred_salary_range=[3734, 5946],
        preferred_language='any',
        preferred_interests=['cooking', 'tech'],
        preferred_personality=[4, 4, 2, 5, 4],
        preferred_height_range=[157, 169],
    ),
    User(
        name='Teh',
        age=31,
        gender='male',
        height=164,
        location='Selangor',
        salary=5884,
        language='Malay',
        interests=['gaming', 'anime', 'tech'],
        personality=[5, 5, 1, 5, 2],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[25, 40],
        preferred_salary_range=[3786, 5983],
        preferred_language='any',
        preferred_interests=['music', 'cooking'],
        preferred_personality=[5, 3, 2, 4, 1],
        preferred_height_range=[155, 169],
    ),
    User(
        name='Pen Yu Yan',
        age=28,
        gender='male',
        height=178,
        location='Melaka',
        salary=8767,
        language='Malay',
        interests=['cooking', 'sports','fitness'],
        personality=[3, 3, 1, 2, 4],
        preferred_gender='female',
        preferred_location='Ipoh',
        preferred_age_range=[25, 30],
        preferred_salary_range=[5465, 8756],
        preferred_language='Malay',
        preferred_interests=['gaming', 'music'],
        preferred_personality=[2, 3, 1, 2, 1],
        preferred_height_range=[160, 170],
    ),
    User(
        name='Pura',
        age=22,
        gender='male',
        height=183,
        location='KL',
        salary=7198,
        language='Malay',
        interests=['gaming', 'travel', 'reading'],
        personality=[5, 2, 2, 4, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 32],
        preferred_salary_range=[4877, 8459],
        preferred_language='Malay',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 4, 4, 1, 4],
        preferred_height_range=[164, 173],
    ),
    User(
        name='Dali',
        age=21,
        gender='male',
        height=180,
        location='KL',
        salary=6778,
        language='Malay',
        interests=['gaming', 'travel', 'reading'],
        personality=[5, 2, 2, 4, 4],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[24, 32],
        preferred_salary_range=[4782, 8459],
        preferred_language='Malay',
        preferred_interests=['sports', 'cooking'],
        preferred_personality=[1, 4, 4, 1, 4],
        preferred_height_range=[163, 171],
    ),
    User(
        name='Xan Yang',
        age=25,
        gender='male',
        height=163,
        location='KL',
        salary=6892,
        language='Malay',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 2, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4871, 7990],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 3, 1, 1],
        preferred_height_range=[155, 173],
    ),
    User(
        name='Knox',
        age=26,
        gender='male',
        height=182,
        location='Ipoh',
        salary=8345,
        language='Malay',
        interests=['cooking', 'reading', 'fitness'],
        personality=[1, 1, 1, 3, 1],
        preferred_gender='female',
        preferred_location='Penang',
        preferred_age_range=[21, 32],
        preferred_salary_range=[3853, 6568],
        preferred_language='any',
        preferred_interests=['anime', 'movies'],
        preferred_personality=[2, 2, 1, 5, 4],
        preferred_height_range=[156, 176],
    ),
    User(
        name='Vsuail',
        age=25,
        gender='male',
        height=161,
        location='KL',
        salary=6892,
        language='Malay',
        interests=['reading', 'anime', 'fitness'],
        personality=[4, 2, 2, 5, 2],
        preferred_gender='female',
        preferred_location='Johor',
        preferred_age_range=[20, 32],
        preferred_salary_range=[4887, 7170],
        preferred_language='any',
        preferred_interests=['sports', 'reading'],
        preferred_personality=[3, 4, 3, 1, 1],
        preferred_height_range=[156, 172],
    ),
]